UPDATE state SET short_name = 'AN' WHERE name = 'Andaman and Nicobar Islands';
UPDATE state SET short_name = 'AP' WHERE name = 'Andhra Pradesh';
UPDATE state SET short_name = 'AR' WHERE name = 'Arunachal Pradesh';
UPDATE state SET short_name = 'AS' WHERE name = 'Assam';
UPDATE state SET short_name = 'BR' WHERE name = 'Bihar';
UPDATE state SET short_name = 'CG' WHERE name = 'Chhattisgarh';
UPDATE state SET short_name = 'GA' WHERE name = 'Goa';
UPDATE state SET short_name = 'GJ' WHERE name = 'Gujarat';
UPDATE state SET short_name = 'HR' WHERE name = 'Haryana';
UPDATE state SET short_name = 'HP' WHERE name = 'Himachal Pradesh';
UPDATE state SET short_name = 'JK' WHERE name = 'Jammu and Kashmir';
UPDATE state SET short_name = 'JH' WHERE name = 'Jharkhand';
UPDATE state SET short_name = 'KA' WHERE name = 'Karnataka';
UPDATE state SET short_name = 'KL' WHERE name = 'Kerala';
UPDATE state SET short_name = 'MP' WHERE name = 'Madhya Pradesh';
UPDATE state SET short_name = 'MH' WHERE name = 'Maharashtra';
UPDATE state SET short_name = 'MN' WHERE name = 'Manipur';
UPDATE state SET short_name = 'ML' WHERE name = 'Meghalaya';
UPDATE state SET short_name = 'MZ' WHERE name = 'Mizoram';
UPDATE state SET short_name = 'NL' WHERE name = 'Nagaland';
UPDATE state SET short_name = 'OR' WHERE name = 'Orissa';
UPDATE state SET short_name = 'PB' WHERE name = 'Punjab';
UPDATE state SET short_name = 'RJ' WHERE name = 'Rajasthan';
UPDATE state SET short_name = 'SK' WHERE name = 'Sikkim';
UPDATE state SET short_name = 'TN' WHERE name = 'Tamil Nadu';
UPDATE state SET short_name = 'TR' WHERE name = 'Tripura';
UPDATE state SET short_name = 'UK' WHERE name = 'Uttarakhand';
UPDATE state SET short_name = 'UP' WHERE name = 'Uttar Pradesh';
UPDATE state SET short_name = 'WB' WHERE name = 'West Bengal';
UPDATE state SET short_name = 'CH' WHERE name = 'Chandigarh';
UPDATE state SET short_name = 'DH' WHERE name = 'Dadra and Nagar Haveli';
UPDATE state SET short_name = 'DD' WHERE name = 'Daman and Diu';
UPDATE state SET short_name = 'DL' WHERE name = 'Delhi';
UPDATE state SET short_name = 'LD' WHERE name = 'Lakshadweep';
UPDATE state SET short_name = 'PY' WHERE name = 'Pondicherry';

UPDATE assessment_tool_mode set short_name = 'N' WHERE name = 'nqas';
UPDATE assessment_tool_mode set short_name = 'K' WHERE name = 'Kayakalp';
UPDATE assessment_tool_mode set short_name = 'L' WHERE name = 'LAQSHYA';

UPDATE assessment_type set short_name = 'In' WHERE name = 'Internal';
UPDATE assessment_type set short_name = 'Ex' WHERE name = 'External';
UPDATE assessment_type set short_name = 'Pr' WHERE name = 'Peer';

UPDATE facility_type set short_name = 'DH' WHERE name = 'District Hospital';
UPDATE facility_type set short_name = 'PHC' WHERE name = 'Primary Health Center';
UPDATE facility_type set short_name = 'CHC' WHERE name = 'Community Health Center';
UPDATE facility_type set short_name = 'UPHC' WHERE name = 'Urban Primary Health Center';
UPDATE facility_type set short_name = 'SDH' WHERE name = 'Sub-Divisional/Taluka Hospital';