update measurable_element set last_modified_date = current_timestamp, name = 'No thoroughfare / general traffic in hospital premises' where id = 1030;
update measurable_element set last_modified_date = current_timestamp, name = 'No water logging in open areas' where id = 1031;
update measurable_element set last_modified_date = current_timestamp, name = 'Open areas are well maintained' where id = 1032;
update measurable_element set last_modified_date = current_timestamp, name = 'There is no unauthorised occupation within the facility, nor there is encroachment on Hospital land' where id = 1033;
update measurable_element set last_modified_date = current_timestamp, name = 'There is no abandoned / dilapidated building within the premises' where id = 1034;
update measurable_element set last_modified_date = current_timestamp, name = 'There is a system of periodical inspection for water wastage' where id = 1035;
update measurable_element set last_modified_date = current_timestamp, name = 'Hospital has a functional rain water harvesting system' where id = 1036;
update measurable_element set last_modified_date = current_timestamp, name = 'Water supply is adequate in Quantity & Quality' where id = 1037;
update measurable_element set last_modified_date = current_timestamp, name = 'Water supply system is maintained in the Hospital' where id = 1038;
update measurable_element set last_modified_date = current_timestamp, name = 'Hospital promotes water conservation' where id = 1039;
update measurable_element set last_modified_date = current_timestamp, name = 'Staff periodically sort useful and unnecessary articles at work station' where id = 1040;
update measurable_element set last_modified_date = current_timestamp, name = 'The Staff arrange the useful articles, records in systematic manner' where id = 1041;
update measurable_element set last_modified_date = current_timestamp, name = 'Staff label the articles in identifiable manner' where id = 1042;
update measurable_element set last_modified_date = current_timestamp, name = 'Staff has been trained for work place management' where id = 1043;
update measurable_element set last_modified_date = current_timestamp, name = 'Work stations are clean and free of dirt/dust' where id = 1044;
update measurable_element set last_modified_date = current_timestamp, name = 'Internal Roads, Pathways, waiting area, etc. are even and clean' where id = 1045;
update measurable_element set last_modified_date = current_timestamp, name = 'Green Areas/ Parks/ Open spaces are well maintained' where id = 1046;
update measurable_element set last_modified_date = current_timestamp, name = 'Facility’s front area is landscaped' where id = 1047;
update measurable_element set last_modified_date = current_timestamp, name = 'Gardens/ green area are secured with fence' where id = 1048;
update measurable_element set last_modified_date = current_timestamp, name = 'Provision of Herbal Garden' where id = 1049;
update measurable_element set last_modified_date = current_timestamp, name = 'Walls are well-plastered and painted' where id = 1050;
update measurable_element set last_modified_date = current_timestamp, name = 'No unwanted/Outdated posters' where id = 1051;
update measurable_element set last_modified_date = current_timestamp, name = 'Interior of patient care areas are plastered & painted' where id = 1052;
update measurable_element set last_modified_date = current_timestamp, name = 'Uniform signage system in the Hospital' where id = 1053;
update measurable_element set last_modified_date = current_timestamp, name = 'Name of the hospital is prominently displayed at the entrance' where id = 1054;
update measurable_element set last_modified_date = current_timestamp, name = 'Measures for Mosquito free environment are in place' where id = 1055;
update measurable_element set last_modified_date = current_timestamp, name = 'Cattle-trap is installed at the entrance' where id = 1056;
update measurable_element set last_modified_date = current_timestamp, name = 'No stray animals within the facility premises' where id = 1057;
update measurable_element set last_modified_date = current_timestamp, name = 'Pest Control Measures are implemented in the facility' where id = 1058;
update measurable_element set last_modified_date = current_timestamp, name = 'Anti-termite Treatment of the wooden furniture and fixtures is undertaken periodically' where id = 1059;
update measurable_element set last_modified_date = current_timestamp, name = 'Hospital has adequate facility for parking of vehicles' where id = 1060;
update measurable_element set last_modified_date = current_timestamp, name = 'Hospital has a system for periodic maintenance of infrastructure at pre-defined interval' where id = 1061;
update measurable_element set last_modified_date = current_timestamp, name = 'Hospital has intact boundary wall and functional gates at entry' where id = 1062;
update measurable_element set last_modified_date = current_timestamp, name = 'Hospital Infrastructure is well maintained' where id = 1063;
update measurable_element set last_modified_date = current_timestamp, name = 'Electric wiring and Fittings are maintained' where id = 1064;
update measurable_element set last_modified_date = current_timestamp, name = 'Adequate illumination in Procedure Areas (Labour Room/ OT)' where id = 1065;
update measurable_element set last_modified_date = current_timestamp, name = 'Use of energy efficient bulbs' where id = 1066;
update measurable_element set last_modified_date = current_timestamp, name = 'Adequate illumination in Circulation Area' where id = 1067;
update measurable_element set last_modified_date = current_timestamp, name = 'Adequate illumination in front of hospital and access road' where id = 1068;
update measurable_element set last_modified_date = current_timestamp, name = 'Adequate illumination in Indoor Areas' where id = 1069;
update measurable_element set last_modified_date = current_timestamp, name = 'There is a system of preventive maintenance of furniture and fixtures' where id = 1070;
update measurable_element set last_modified_date = current_timestamp, name = 'Window and doors are maintained' where id = 1071;
update measurable_element set last_modified_date = current_timestamp, name = 'Furniture at the nursing station, staff room, administrative office are maintained' where id = 1072;
update measurable_element set last_modified_date = current_timestamp, name = 'Patient Beds & Mattresses are in good condition' where id = 1073;
update measurable_element set last_modified_date = current_timestamp, name = 'Trolleys, Stretchers, Wheel Chairs, etc. are well maintained' where id = 1074;
update measurable_element set last_modified_date = current_timestamp, name = 'No junk material in critical service area' where id = 1075;
update measurable_element set last_modified_date = current_timestamp, name = 'No junk material in Open Areas and corridors' where id = 1076;
update measurable_element set last_modified_date = current_timestamp, name = 'Hospital has demarcated space for keeping condemned junk material' where id = 1077;
update measurable_element set last_modified_date = current_timestamp, name = 'Hospital has documented and implemented Condemnation policy' where id = 1078;
update measurable_element set last_modified_date = current_timestamp, name = 'No junk material in patient care areas' where id = 1079;
update measurable_element set last_modified_date = current_timestamp, name = 'No Cobwebs/Bird Nest/ Dust on walls and roofs of corridors' where id = 1080;
update measurable_element set last_modified_date = current_timestamp, name = 'Corridors are cleaned at least twice in the day with wet mop' where id = 1081;
update measurable_element set last_modified_date = current_timestamp, name = 'Corridors are rigorously cleaned with scrubbing / flooding once in a month' where id = 1082;
update measurable_element set last_modified_date = current_timestamp, name = 'No dirt/Grease/Stains in the Circulation area' where id = 1083;
update measurable_element set last_modified_date = current_timestamp, name = 'Surfaces are conducive of effective cleaning' where id = 1084;
update measurable_element set last_modified_date = current_timestamp, name = 'Floors, walls, furniture and fixture are thoroughly cleaned once in a month' where id = 1085;
update measurable_element set last_modified_date = current_timestamp, name = 'No dirt/Grease/ Stains/ Garbage in Auxiliary Area' where id = 1086;
update measurable_element set last_modified_date = current_timestamp, name = 'No Cobwebs/Bird Nest/ Seepage on walls and roofs of Auxiliary Area' where id = 1087;
update measurable_element set last_modified_date = current_timestamp, name = 'Furniture & Fixtures are without grease and dust and cleaned daily' where id = 1088;
update measurable_element set last_modified_date = current_timestamp, name = 'Auxiliary Areas are cleaned at least twice in the day with wet mop' where id = 1089;
update measurable_element set last_modified_date = current_timestamp, name = 'Use of Three bucket system for cleaning' where id = 1090;
update measurable_element set last_modified_date = current_timestamp, name = 'Use of separate mops for critical and semi critical areas and procedures surfaces' where id = 1091;
update measurable_element set last_modified_date = current_timestamp, name = 'Disinfection and washing of mops after every cleaning cycle' where id = 1092;
update measurable_element set last_modified_date = current_timestamp, name = 'Use unidirectional method and out word mopping' where id = 1093;
update measurable_element set last_modified_date = current_timestamp, name = 'No use of brooms in patient care areas' where id = 1094;
update measurable_element set last_modified_date = current_timestamp, name = 'All the drains are cleaned once in a week' where id = 1095;
update measurable_element set last_modified_date = current_timestamp, name = 'Gradient of Drains is conducive for adequate for maintaining flow' where id = 1096;
update measurable_element set last_modified_date = current_timestamp, name = 'No blocked/ over-flowing drains in the facility' where id = 1097;
update measurable_element set last_modified_date = current_timestamp, name = 'Availability of connection with Municipal Sewage System/ or Soak Pit' where id = 1098;
update measurable_element set last_modified_date = current_timestamp, name = 'Availability of closed drainage system' where id = 1099;
update measurable_element set last_modified_date = current_timestamp, name = 'No dirt/Grease/ Stains/ Garbage in wards' where id = 1100;
update measurable_element set last_modified_date = current_timestamp, name = 'Wards are cleaned at least thrice in the day with wet mop' where id = 1101;
update measurable_element set last_modified_date = current_timestamp, name = 'Floors, walls, furniture and fixture are thoroughly cleaned once in a week.' where id = 1102;
update measurable_element set last_modified_date = current_timestamp, name = 'No Cobwebs/Bird Nest/ Dust/Seepage on walls and roofs of wards' where id = 1103;
update measurable_element set last_modified_date = current_timestamp, name = 'Patient Furniture, Mattresses, Fixtures are without grease and dust' where id = 1104;
update measurable_element set last_modified_date = current_timestamp, name = 'Floors, walls, furniture and fixture are thoroughly cleaned once in a week.' where id = 1105;
update measurable_element set last_modified_date = current_timestamp, name = 'OT/Labour Room floors and procedures surfaces are cleaned at least twice a day / after every surgery' where id = 1106;
update measurable_element set last_modified_date = current_timestamp, name = 'No dirt/Grease/ Stains/ Garbage in Procedure Areas' where id = 1107;
update measurable_element set last_modified_date = current_timestamp, name = 'No Cobwebs/Bird Nest/ Seepage in OT & Labour Room' where id = 1108;
update measurable_element set last_modified_date = current_timestamp, name = 'OT & Labour Room Tables are without grease, body fluid and dust' where id = 1109;
update measurable_element set last_modified_date = current_timestamp, name = 'Use of Housekeeping Checklist in Toilets' where id = 1110;
update measurable_element set last_modified_date = current_timestamp, name = 'Use of Housekeeping Checklist in Patient Care Areas' where id = 1111;
update measurable_element set last_modified_date = current_timestamp, name = 'A person is designated for monitoring of Housekeeping Activities' where id = 1112;
update measurable_element set last_modified_date = current_timestamp, name = 'Monitoring of adequacy and quality of material used for cleaning' where id = 1113;
update measurable_element set last_modified_date = current_timestamp, name = 'Use of Housekeeping Checklist in Procedure Areas' where id = 1114;
update measurable_element set last_modified_date = current_timestamp, name = 'Toilets have running water and functional cistern' where id = 1115;
update measurable_element set last_modified_date = current_timestamp, name = 'Floors of Toilets are Dry' where id = 1116;
update measurable_element set last_modified_date = current_timestamp, name = 'No foul smell in the Toilets' where id = 1117;
update measurable_element set last_modified_date = current_timestamp, name = 'No dirt/Grease/Stains/ Garbage in Toilets' where id = 1118;
update measurable_element set last_modified_date = current_timestamp, name = 'Sinks and Cistern are cleaned every two hours or whenever required' where id = 1119;
update measurable_element set last_modified_date = current_timestamp, name = 'Availability of Detergent Disinfectant solution / Hospital Grade Phenyl for Cleaning purpose' where id = 1120;
update measurable_element set last_modified_date = current_timestamp, name = 'Availability of carbolic Acid/ Bacilocid for surface cleaning in procedure areas- OT, Labour Room' where id = 1121;
update measurable_element set last_modified_date = current_timestamp, name = 'Availability of Buckets and carts for Mopping' where id = 1122;
update measurable_element set last_modified_date = current_timestamp, name = 'Availability of Cleaning Equipment' where id = 1123;
update measurable_element set last_modified_date = current_timestamp, name = 'Cleaning staff uses correct concentration of cleaning solution' where id = 1124;
update measurable_element set last_modified_date = current_timestamp, name = 'No Cobwebs/Bird Nest/ Seepage on walls and roofs of ambulatory area' where id = 1125;
update measurable_element set last_modified_date = current_timestamp, name = 'Ambulatory Areas are cleaned at least thrice in the day with wet mop' where id = 1126;
update measurable_element set last_modified_date = current_timestamp, name = 'No dirt/Grease/Stains / Garbage in Ambulatory Area' where id = 1127;
update measurable_element set last_modified_date = current_timestamp, name = 'Floors, walls, furniture and fixture are thoroughly cleaned once in a week.' where id = 1128;
update measurable_element set last_modified_date = current_timestamp, name = 'Furniture, & Fixtures are without grease and dust and cleaned daily' where id = 1129;
update measurable_element set last_modified_date = current_timestamp, name = 'Recyclable and Biodegradable Wastes have segregated collection ' where id = 1130;
update measurable_element set last_modified_date = current_timestamp, name = 'The Facility Undertakes efforts to educate patients and visitors about segregation of recyclable and biodegradable wastes' where id = 1131;
update measurable_element set last_modified_date = current_timestamp, name = 'Availability of Compost Pit within the premises' where id = 1132;
update measurable_element set last_modified_date = current_timestamp, name = 'General Waste is not mixed with infected waste' where id = 1133;
update measurable_element set last_modified_date = current_timestamp, name = 'The facility has introduced innovations in managing General Waste' where id = 1134;
update measurable_element set last_modified_date = current_timestamp, name = 'The facility has started undertaking actions, which are to be complied by March 2019' where id = 1135;
update measurable_element set last_modified_date = current_timestamp, name = 'The facility has implemented Biomedical Waste Rules' where id = 1136;
update measurable_element set last_modified_date = current_timestamp, name = 'An existing committee or newly constituted committee for review and monitoring of BMW management at DH/CHC level' where id = 1137;
update measurable_element set last_modified_date = current_timestamp, name = 'The Hospital leadership is aware of Biomedical Waste Rules 2016 including key changes as amendments.' where id = 1138;
update measurable_element set last_modified_date = current_timestamp, name = 'The facility has started undertaking actions for bar coding system' where id = 1139;
update measurable_element set last_modified_date = current_timestamp, name = 'Disinfected Glassware is stored as per protocol given in Schedule I of the BMW Rules 2016 and amendments .' where id = 1140;
update measurable_element set last_modified_date = current_timestamp, name = 'Staff is aware of needle stick injury Protocol and PEP is available to the staff ' where id = 1141;
update measurable_element set last_modified_date = current_timestamp, name = 'Staff is aware of needle stick injury Protocol and PEP is available to the staff ' where id = 1141;
update measurable_element set last_modified_date = current_timestamp, name = 'Disinfection of Broken / Discarded Glassware is done as per recommended procedure' where id = 1142;
update measurable_element set last_modified_date = current_timestamp, name = 'The Staff uses needle cutters for cutting/burning the syringe hub' where id = 1143;
update measurable_element set last_modified_date = current_timestamp, name = 'Discarded / contaminated linen is disposed as per procedure given in the BMW Rules 2016' where id = 1144;
update measurable_element set last_modified_date = current_timestamp, name = 'The Health Facility has adequate arrangements for disposal of Biomedical waste' where id = 1145;
update measurable_element set last_modified_date = current_timestamp, name = 'Deep Burial Pit is constructed as per norms given in the Biomedical Waste Rules 2016' where id = 1146;
update measurable_element set last_modified_date = current_timestamp, name = 'Disposal of Expired or discarded medicine is done as per protocol given in Schedule I of BMW Rules 2016' where id = 1147;
update measurable_element set last_modified_date = current_timestamp, name = 'Recyclable waste is disposed as per procedure given in the BMW Rules 2016' where id = 1148;
update measurable_element set last_modified_date = current_timestamp, name = 'Availability of Bins and liners  for segregated collection of waste at point of use' where id = 1149;
update measurable_element set last_modified_date = current_timestamp, name = 'Availability of Needle/ Hub cutter and puncture proof boxes' where id = 1150;
update measurable_element set last_modified_date = current_timestamp, name = 'Availability of Sodium Hypochlorite Solution' where id = 1151;
update measurable_element set last_modified_date = current_timestamp, name = 'Availability of trolleys for waste collection and transportation' where id = 1152;
update measurable_element set last_modified_date = current_timestamp, name = 'Availability and supply of personal protective equipment ' where id = 1153;
update measurable_element set last_modified_date = current_timestamp, name = 'Availability of Mercury Spill Management Kit ' where id = 1154;
update measurable_element set last_modified_date = current_timestamp, name = 'The Staff is aware of Mercury Spill management ' where id = 1155;
update measurable_element set last_modified_date = current_timestamp, name = 'Disposal of Disinfectant solution like Glutaraldehyde ' where id = 1156;
update measurable_element set last_modified_date = current_timestamp, name = 'Disposal of Radiographic Developer and Fixer ' where id = 1157;
update measurable_element set last_modified_date = current_timestamp, name = 'Disposal of Radiographic Developer and Fixer ' where id = 1157;
update measurable_element set last_modified_date = current_timestamp, name = 'Runoff is drained into the municipal drain' where id = 1158;
update measurable_element set last_modified_date = current_timestamp, name = 'Sullage is managed scientifically' where id = 1159;
update measurable_element set last_modified_date = current_timestamp, name = 'The laboratory has a functional protocol for managing discarded samples ' where id = 1160;
update measurable_element set last_modified_date = current_timestamp, name = 'Body fluids, Secretions in suction apparatus, blood and other exudates in OT, Labour room, minor OT, Dressing room are disposed only after treatment' where id = 1161;
update measurable_element set last_modified_date = current_timestamp, name = 'The Facility has treatment facility for managing infectious liquid waste ' where id = 1162;
update measurable_element set last_modified_date = current_timestamp, name = 'Segregation of BMW is done as per BMW management rule,2016 ' where id = 1163;
update measurable_element set last_modified_date = current_timestamp, name = 'Biomedical waste bins are covered' where id = 1164;
update measurable_element set last_modified_date = current_timestamp, name = 'Work instructions for segregation and handling of Biomedical waste has been displayed prominently' where id = 1165;
update measurable_element set last_modified_date = current_timestamp, name = 'The facility has linkage with a CWTF Operator or has deep burial pit (with prior approval of the prescribed authority)' where id = 1166;
update measurable_element set last_modified_date = current_timestamp, name = 'Transportation of biomedical waste is done in closed container/trolley' where id = 1167;
update measurable_element set last_modified_date = current_timestamp, name = 'Dedicated Storage facility is available for biomedical waste and its has biohazard symbol displayed' where id = 1168;
update measurable_element set last_modified_date = current_timestamp, name = 'No Biomedical waste is stored for more than 48 Hours' where id = 1169;
update measurable_element set last_modified_date = current_timestamp, name = 'The Storage facility  is secured against pilferage and reach of animal and rodents. ' where id = 1170;
update measurable_element set last_modified_date = current_timestamp, name = 'The Storage facility is located away from the patient area and has connectivity of a motor able road.' where id = 1171;
update measurable_element set last_modified_date = current_timestamp, name = 'The storage facility has hand-washing facilities for the workers' where id = 1172;
update measurable_element set last_modified_date = current_timestamp, name = 'The Health facility maintains its website and annual report is uploaded' where id = 1173;
update measurable_element set last_modified_date = current_timestamp, name = 'The Health Facility has a system of review and monitoring of BMW Management through an existing committee or by forming a new committee' where id = 1174;
update measurable_element set last_modified_date = current_timestamp, name = 'The Health Facility has a valid authorization for Bio Medical waste Management from the prescribed authority' where id = 1175;
update measurable_element set last_modified_date = current_timestamp, name = 'The Health Facility maintains records, as required under the Biomedical Waste Rules 2016' where id = 1176;
update measurable_element set last_modified_date = current_timestamp, name = 'The Health Facility submits Annual report to pollution control board' where id = 1177;
update measurable_element set last_modified_date = current_timestamp, name = 'Regular microbiological surveillance of Critical areas' where id = 1178;
update measurable_element set last_modified_date = current_timestamp, name = 'Hospital measures Surgical Site Infection Rates' where id = 1179;
update measurable_element set last_modified_date = current_timestamp, name = 'Hospital measures Device Related HAI rates' where id = 1180;
update measurable_element set last_modified_date = current_timestamp, name = 'Hospital takes corrective Action on occurrence of HAIs' where id = 1181;
update measurable_element set last_modified_date = current_timestamp, name = 'Hospital measures Blood Related and Respiratory Tract HAI' where id = 1182;
update measurable_element set last_modified_date = current_timestamp, name = 'Maintenance of air exchanges in OT and ICU' where id = 1183;
update measurable_element set last_modified_date = current_timestamp, name = 'Maintenance of positive air pressure in OT and ICU' where id = 1184;
update measurable_element set last_modified_date = current_timestamp, name = 'Carbolization of OT and Labour Room' where id = 1185;
update measurable_element set last_modified_date = current_timestamp, name = 'Maintenance of Layout in OT' where id = 1186;
update measurable_element set last_modified_date = current_timestamp, name = 'General and patient traffic are segregated in Hospitals' where id = 1187;
update measurable_element set last_modified_date = current_timestamp, name = 'Correct method of wearing and removing gloves' where id = 1188;
update measurable_element set last_modified_date = current_timestamp, name = 'Correct Method of wearing mask and cap' where id = 1189;
update measurable_element set last_modified_date = current_timestamp, name = 'The Staff is aware of Standard Precautions' where id = 1190;
update measurable_element set last_modified_date = current_timestamp, name = 'The staff is aware of use of gloves, when to use (occasion) and its type' where id = 1191;
update measurable_element set last_modified_date = current_timestamp, name = 'No re-use of disposable personal protective equipment' where id = 1192;
update measurable_element set last_modified_date = current_timestamp, name = 'Sterility of autoclaved pack maintained during storage' where id = 1193;
update measurable_element set last_modified_date = current_timestamp, name = 'Adherence to Protocols for autoclaving' where id = 1194;
update measurable_element set last_modified_date = current_timestamp, name = 'Chemical Sterilization of instruments done as per protocol' where id = 1195;
update measurable_element set last_modified_date = current_timestamp, name = 'Adherence to Protocol for High Level disinfection' where id = 1196;
update measurable_element set last_modified_date = current_timestamp, name = 'Use of Signal Locks for sterilization' where id = 1197;
update measurable_element set last_modified_date = current_timestamp, name = 'Availability of spill management Kit' where id = 1198;
update measurable_element set last_modified_date = current_timestamp, name = 'Staff is aware of management of large spills' where id = 1199;
update measurable_element set last_modified_date = current_timestamp, name = 'Staff is aware of how manage small spills' where id = 1200;
update measurable_element set last_modified_date = current_timestamp, name = 'Spill management protocols are displayed at points if use' where id = 1201;
update measurable_element set last_modified_date = current_timestamp, name = 'Staff has been trained for spill management' where id = 1202;
update measurable_element set last_modified_date = current_timestamp, name = 'Infection Control Committee is constituted and functional in the Hospital' where id = 1203;
update measurable_element set last_modified_date = current_timestamp, name = 'Regular Monitoring of infection control practices' where id = 1204;
update measurable_element set last_modified_date = current_timestamp, name = 'Antibiotic Policy is implemented at the facility' where id = 1205;
update measurable_element set last_modified_date = current_timestamp, name = 'Immunization of Service Providers' where id = 1206;
update measurable_element set last_modified_date = current_timestamp, name = 'Regular Medical check- ups of food handlers and housekeeping staff' where id = 1207;
update measurable_element set last_modified_date = current_timestamp, name = 'Restriction of visitors to Isolation Area' where id = 1208;
update measurable_element set last_modified_date = current_timestamp, name = 'Maintenance of adequate bed to bed distance in wards' where id = 1209;
update measurable_element set last_modified_date = current_timestamp, name = 'Infectious patients are not mixed for general patients' where id = 1210;
update measurable_element set last_modified_date = current_timestamp, name = 'Provision of Isolation ward' where id = 1211;
update measurable_element set last_modified_date = current_timestamp, name = 'Restriction of external foot wear in critical areas' where id = 1212;
update measurable_element set last_modified_date = current_timestamp, name = 'Availability of Sink and running water at point of use' where id = 1213;
update measurable_element set last_modified_date = current_timestamp, name = 'Staff is aware of when to hand wash' where id = 1214;
update measurable_element set last_modified_date = current_timestamp, name = 'Display of Hand washing Instructions' where id = 1215;
update measurable_element set last_modified_date = current_timestamp, name = 'Availability of Alcohol Based hand rub' where id = 1216;
update measurable_element set last_modified_date = current_timestamp, name = 'Adherence to 6 steps of Hand washing' where id = 1217;
update measurable_element set last_modified_date = current_timestamp, name = 'Use of Masks and Head cap' where id = 1218;
update measurable_element set last_modified_date = current_timestamp, name = 'Adequate supply of Personal Protective Equipment (PPE)' where id = 1219;
update measurable_element set last_modified_date = current_timestamp, name = 'Use of Heavy Duty Gloves and gumboot by waste handlers' where id = 1220;
update measurable_element set last_modified_date = current_timestamp, name = 'Use of Gloves during procedures and examination' where id = 1221;
update measurable_element set last_modified_date = current_timestamp, name = 'Use of aprons/ Lab coat by the clinical staff' where id = 1222;
update measurable_element set last_modified_date = current_timestamp, name = 'Decontamination of instruments after use' where id = 1223;
update measurable_element set last_modified_date = current_timestamp, name = 'Decontamination of operating and Surface examination table, dressing tables etc. after every procedures' where id = 1224;
update measurable_element set last_modified_date = current_timestamp, name = 'Cleaning of instruments done after decontamination' where id = 1225;
update measurable_element set last_modified_date = current_timestamp, name = 'Staff knows how to make Chlorine solution' where id = 1226;
update measurable_element set last_modified_date = current_timestamp, name = 'Adequate Contact Time for decontamination' where id = 1227;
update measurable_element set last_modified_date = current_timestamp, name = 'Hospital kitchen is located in a separate building, away from patient care area and functions meticulously' where id = 1228;
update measurable_element set last_modified_date = current_timestamp, name = 'Staff observes meticulous personal hygiene' where id = 1229;
update measurable_element set last_modified_date = current_timestamp, name = 'The Kitchen is smoke-free and fly-proofed' where id = 1230;
update measurable_element set last_modified_date = current_timestamp, name = 'The Kitchen has provision to store dry ration and fresh ration separately.' where id = 1231;
update measurable_element set last_modified_date = current_timestamp, name = 'Food to patients is distributed through covered trolleys and patients utensils are not dented or chipped - off' where id = 1232;
update measurable_element set last_modified_date = current_timestamp, name = 'The facility has adequate stock (including reserve) of linen' where id = 1233;
update measurable_element set last_modified_date = current_timestamp, name = 'Patients’ dress are clean and not torn' where id = 1234;
update measurable_element set last_modified_date = current_timestamp, name = 'Bed-sheets and pillow cover are stain free and clean' where id = 1235;
update measurable_element set last_modified_date = current_timestamp, name = 'Soiled linen is removed, segregated and disinfected, as per procedure' where id = 1236;
update measurable_element set last_modified_date = current_timestamp, name = 'Bed-sheets and linen are changed daily' where id = 1237;
update measurable_element set last_modified_date = current_timestamp, name = 'The Contract has well defined measurable deliverables' where id = 1238;
update measurable_element set last_modified_date = current_timestamp, name = 'Services provided by the out-sourced organisation are measured periodically and performance evaluation is formally recorded.' where id = 1239;
update measurable_element set last_modified_date = current_timestamp, name = 'The contract has penalty clause and it has been evoked in the event of non- performance or sub-standard performance' where id = 1240;
update measurable_element set last_modified_date = current_timestamp, name = 'There is valid contract for out-sourced services, like house-keeping, BMW management, security, etc.' where id = 1241;
update measurable_element set last_modified_date = current_timestamp, name = 'There is defined time-line for release of payment to the contractors for the services delivered by the organisation.' where id = 1242;
update measurable_element set last_modified_date = current_timestamp, name = 'Security personal reprimands attendants, who found indulging into unhygienic behaviour - spitting, open field urination & defecation, etc.' where id = 1243;
update measurable_element set last_modified_date = current_timestamp, name = 'The main gate of premises, Hospital building, wards, OT and Labour room are secured' where id = 1244;
update measurable_element set last_modified_date = current_timestamp, name = 'There is a robust crowd management system.' where id = 1245;
update measurable_element set last_modified_date = current_timestamp, name = 'The security personal are meticulously dressed and smartly turned-out.' where id = 1246;
update measurable_element set last_modified_date = current_timestamp, name = 'Un-authorised vendors are not present inside the campus. Waste storage is secured and there is no plastic items, card board etc.' where id = 1247;
update measurable_element set last_modified_date = current_timestamp, name = 'Water is available at all points of use' where id = 1248;
update measurable_element set last_modified_date = current_timestamp, name = 'There is storage tank for the water and tank is cleaned periodically' where id = 1249;
update measurable_element set last_modified_date = current_timestamp, name = 'Drinking Water is chlorinated' where id = 1250;
update measurable_element set last_modified_date = current_timestamp, name = 'The facility receives adequate quantity of water as per requirement' where id = 1251;
update measurable_element set last_modified_date = current_timestamp, name = 'Quality of Water is tested periodically' where id = 1252;
update measurable_element set last_modified_date = current_timestamp, name = 'Nursing staff adhere to designated dress code' where id = 1253;
update measurable_element set last_modified_date = current_timestamp, name = 'Support and Housekeeping staff adhere to their designated dress code' where id = 1254;
update measurable_element set last_modified_date = current_timestamp, name = 'Identity cards and name plates have been provided to all staff' where id = 1255;
update measurable_element set last_modified_date = current_timestamp, name = 'Hospital has dress code policy for all cadre of staff' where id = 1256;
update measurable_element set last_modified_date = current_timestamp, name = 'There is a regular monitoring of hygiene practices of food handlers and housekeeping staff' where id = 1257;
update measurable_element set last_modified_date = current_timestamp, name = 'IEC regarding water sanitation is displayed in the hospital premises' where id = 1258;
update measurable_element set last_modified_date = current_timestamp, name = 'IEC regarding Swachhata Abhiyan is displayed within the facilities’ premises' where id = 1259;
update measurable_element set last_modified_date = current_timestamp, name = 'IEC regarding importance of maintaining hand hygiene is displayed in hospital premises' where id = 1260;
update measurable_element set last_modified_date = current_timestamp, name = 'Hospital disseminates hygiene messages through other innovative manners' where id = 1261;
update measurable_element set last_modified_date = current_timestamp, name = 'IEC regarding use of toilets is displayed within hospital premises' where id = 1262;
update measurable_element set last_modified_date = current_timestamp, name = 'Hospital conducts are training need assessment regarding cleanliness and infection control in hospital' where id = 1263;
update measurable_element set last_modified_date = current_timestamp, name = 'Hospital has documented Standard Operating procedures for Bio-Medical waste management and Infection Control' where id = 1264;
update measurable_element set last_modified_date = current_timestamp, name = 'Infection control Training has been provided to the staff' where id = 1265;
update measurable_element set last_modified_date = current_timestamp, name = 'Bio medical waste Management training has been provided to the staff' where id = 1266;
update measurable_element set last_modified_date = current_timestamp, name = 'Hospital has documented Standard Operating procedures for Cleanliness and Upkeep of Facility' where id = 1267;
update measurable_element set last_modified_date = current_timestamp, name = 'Patients are counselled on benefits of Hygiene' where id = 1268;
update measurable_element set last_modified_date = current_timestamp, name = 'Patients are made aware of their responsibility of keeping the health facility clean' where id = 1269;
update measurable_element set last_modified_date = current_timestamp, name = 'The Health facility has a system to take feed-back from patients and visitors for maintaining the cleanliness of the facility' where id = 1270;
update measurable_element set last_modified_date = current_timestamp, name = 'Local NGO/ Civil Society Organizations are involved in cleanliness of the hospital' where id = 1271;
update measurable_element set last_modified_date = current_timestamp, name = 'Members of RKS and Local Governance bodies monitor the cleanliness of the hospital at pre-defined intervals' where id = 1272;
update measurable_element set last_modified_date = current_timestamp, name = 'Roles and responsibility of different staff members have been assigned and communicated' where id = 1273;
update measurable_element set last_modified_date = current_timestamp, name = 'Cleanliness and infection control committee has representation of all cadre of staff including Group ‘D’ and cleanings staff' where id = 1274;
update measurable_element set last_modified_date = current_timestamp, name = 'Cleanliness and Infection control committee is constituted at the facility' where id = 1275;
update measurable_element set last_modified_date = current_timestamp, name = 'Hospital leadership review the progress of the cleanliness drive on weekly basis' where id = 1276;
update measurable_element set last_modified_date = current_timestamp, name = 'Hospitals leadership identifies good performing staff members and departments' where id = 1277;
update measurable_element set last_modified_date = current_timestamp, name = 'Surrounding area is declared Open Defecation Free' where id = 1859;
update measurable_element set last_modified_date = current_timestamp, name = 'Measure to control noise pollution in Surrounding area' where id = 1860;
update measurable_element set last_modified_date = current_timestamp, name = 'Measure to control air pollution in surrounding area' where id = 1861;
update measurable_element set last_modified_date = current_timestamp, name = 'Promotion of water conservation' where id = 1862;
update measurable_element set last_modified_date = current_timestamp, name = 'A person is designated to supervise and monitor activities related to cleanliness, sanitation and hygiene in surrounding area' where id = 1863;
update measurable_element set last_modified_date = current_timestamp, name = 'The facility engages the local Community for reducing household pollutions in the vicinity' where id = 1864;
update measurable_element set last_modified_date = current_timestamp, name = 'The Facility endeavours to attract support under the  Corporate social responsibility & initiative' where id = 1865;
update measurable_element set last_modified_date = current_timestamp, name = 'Facility coordinate with local school/ college ' where id = 1866;
update measurable_element set last_modified_date = current_timestamp, name = 'The Facility endeavours to attract support from the local support' where id = 1867;
update measurable_element set last_modified_date = current_timestamp, name = 'The Facility endeavours to attract support from Philanthropic Organisations' where id = 1868;
update measurable_element set last_modified_date = current_timestamp, name = 'No unwanted/broken/ torn / loose hanging posters/ billboards.' where id = 1869;
update measurable_element set last_modified_date = current_timestamp, name = 'Parks and green areas in the surrounding area are well maintained' where id = 1870;
update measurable_element set last_modified_date = current_timestamp, name = 'Illumination in surrounding area' where id = 1871;
update measurable_element set last_modified_date = current_timestamp, name = 'No loose hanging wires in and around the bill-boards, electric poles, etc' where id = 1872;
update measurable_element set last_modified_date = current_timestamp, name = 'There are no stray animals in surrounding area' where id = 1873;
update measurable_element set last_modified_date = current_timestamp, name = 'On the way signage''s are available' where id = 1874;
update measurable_element set last_modified_date = current_timestamp, name = 'Approach roads are wide enough for smooth traffic flow' where id = 1875;
update measurable_element set last_modified_date = current_timestamp, name = 'No unauthorised encroachments alongside of approach road' where id = 1876;
update measurable_element set last_modified_date = current_timestamp, name = 'Approach roads are even and free from pot-holes' where id = 1877;
update measurable_element set last_modified_date = current_timestamp, name = 'Functional street lights are available along the approach road' where id = 1878;
update measurable_element set last_modified_date = current_timestamp, name = 'Availability of bins for general recyclable and biodegradable wastes' where id = 1879;
update measurable_element set last_modified_date = current_timestamp, name = 'Segregation of general waste is done' where id = 1880;
update measurable_element set last_modified_date = current_timestamp, name = 'Implementation of IEC activities related to '' Swachh Bharat Abhiyan''' where id = 1881;
update measurable_element set last_modified_date = current_timestamp, name = 'Community awareness by organising physical activities' where id = 1882;
update measurable_element set last_modified_date = current_timestamp, name = 'Community awareness by organising cultural programs' where id = 1883;
update measurable_element set last_modified_date = current_timestamp, name = 'Local community actively participates during Swachhata Pakhwara (fortnight)' where id = 1884;
update measurable_element set last_modified_date = current_timestamp, name = 'Community awareness through competition and rewards' where id = 1885;
update measurable_element set last_modified_date = current_timestamp, name = 'The Facility coordinates with other Department for improving sanitation and hygiene in the surroundings' where id = 1886;
update measurable_element set last_modified_date = current_timestamp, name = 'The Facility has linkage with Local NGOs, who work in the area of water, sanitation and hygiene' where id = 1887;
update measurable_element set last_modified_date = current_timestamp, name = 'The Facility coordinates with the local Municipal corporation/ PRI for improving the sanitation and hygiene' where id = 1888;
update measurable_element set last_modified_date = current_timestamp, name = 'The Facility coordinates with nearby schools & colleges, National Service Scheme, NSG (National Scouts and Guides), NCC (National Cadet Core), etc. for promotion of hygiene & sanitation' where id = 1889;
update measurable_element set last_modified_date = current_timestamp, name = 'The Facility coordinates with nearby market welfare associations, Resident Welfare associations, etc. for improving & maintaining sanitation and hygiene in surrounding area' where id = 1890;
update measurable_element set last_modified_date = current_timestamp, name = 'Availability of Public toilets in surrounding Area' where id = 1891;
update measurable_element set last_modified_date = current_timestamp, name = 'Public toilets & urinal in surrounding areas are clean' where id = 1892;
update measurable_element set last_modified_date = current_timestamp, name = 'Availability of adequate parking stand ' where id = 1893;
update measurable_element set last_modified_date = current_timestamp, name = 'Presence of safe drinking water facility outside the health facility' where id = 1894;
update measurable_element set last_modified_date = current_timestamp, name = 'Availability of urinals in surrounding area' where id = 1895;
update measurable_element set last_modified_date = current_timestamp, name = 'Surrounding areas are well maintained' where id = 1896;
update measurable_element set last_modified_date = current_timestamp, name = 'Periodic cleaning of dust bins and garbage storage area' where id = 1897;
update measurable_element set last_modified_date = current_timestamp, name = 'Regular cleaning of drains' where id = 1898;
update measurable_element set last_modified_date = current_timestamp, name = 'Vector control measures are taken for disease prevention.' where id = 1899;
update measurable_element set last_modified_date = current_timestamp, name = 'Regular repairs and maintained of roads, footpaths and pavements ' where id = 1900;
update measurable_element set last_modified_date = current_timestamp, name = 'All drains and sewer are covered. ' where id = 1901;
update measurable_element set last_modified_date = current_timestamp, name = 'Footpaths and pavements are clean' where id = 1902;
update measurable_element set last_modified_date = current_timestamp, name = 'Area around the Facility is clean, neat & tidy' where id = 1903;
update measurable_element set last_modified_date = current_timestamp, name = 'Exterior of hospital boundary wall is painted and maintained' where id = 1904;
update measurable_element set last_modified_date = current_timestamp, name = 'No water logging in surrounding area.' where id = 1905;