update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'No stray animals within the facility premises', means_of_verification = 'Observe for the presence of stray animals such as dogs, cats, cattle, pigs, etc. within the premises. Also discuss with the facility staff.
Check at the entrance of the facility that cattle trap has been provided.' where id = 13338;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = TRUE, am_record_review = FALSE, name = 'Measures for Mosquito free environment are in place', means_of_verification = 'Check for
a. Wire Mesh in windows                                  b. Desert Coolers (if in use) are cleaned regularly/ oil is sprinkled                                  c. No water collection to prevent mosquito breeding within the premises
d. Gambusia fish cultivation
e. Usage of Mosquito nets by the admitted patients
f. Availability of adequate stock of Mosquito nets( If Applicable)           ' where id = 13339;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Pest Control Measures are implemented in the facility', means_of_verification = 'Check for the evidence at the facility (Presence of Pests, Record of Purchase of Pesticides and availability of the rat trap) and Interview the staff about its usage ' where id = 13340;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'PHC has a functional rain water harvesting system', means_of_verification = 'If the such system is available, please check its functionality' where id = 13341;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Preventive measures are taken to reduce wastage and reuse of water', means_of_verification = 'Check self closing taps are installed
Reuse of water for activities like gardening.' where id = 13342;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Water supply system is maintained in the PHC', means_of_verification = 'Check for leaking taps, pipes, over-flowing tanks and dysfunctional cisterns' where id = 13343;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'There is no abandoned / dilapidated building within the premises', means_of_verification = 'Check for presence of any ‘abandoned building’ within the facility premises' where id = 13344;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'There is no unauthorised occupation within the facility, nor there is encroachment on PHC land', means_of_verification = 'Check for PHC premises and access road have not been encroached by the vendors, unauthorized shops/ occupants,
No thoroughfare / general traffic in PHC premises etc.' where id = 13345;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'No water logging in open areas', means_of_verification = 'Check for water accumulation in open areas because of faulty drainage, leakage from the pipes, etc.' where id = 13346;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Internal Roads, Pathways, etc. are uneven and clean', means_of_verification = 'Check that pathways, corridors, courtyards, etc. are clean and landscaped.' where id = 13347;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Provision of Herbal Garden', means_of_verification = 'Check if the facility maintains a herbal garden for the medicinal plants' where id = 13348;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Front area/ Parks/ Open spaces are well maintained', means_of_verification = 'Check that wild vegetation does not exist. Shrubs and Trees are well maintained. Over grown branches of plants/ tree have been trimmed regularly.                                                Dry leaves and green waste are removed on daily basis.
Gardens/ green area are secured with fence' where id = 13349;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Walls are well-plastered and painted', means_of_verification = 'Check that wall (Internal and External) plaster is not chipped-off and the building is painted/ whitewashed in uniform approved colour and Paint has not faded away.
Check for presence of any outdated Posters' where id = 13350;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Uniform signage system in the PHC', means_of_verification = 'All signage''s (directional & departmental) are in local language and follow uniform colour scheme.' where id = 13351;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Name of the PHC is prominently displayed at the entrance', means_of_verification = 'Name  of the PHC is prominently displayed as per state’s policy.
  The name board of the facility is well illuminated / florescent to have visibility in night' where id = 13352;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Window and doors are maintained', means_of_verification = 'Check, if Window panes are intact, and provided with Grill/ Wire Mesh. Doors are intact and painted /varnished' where id = 13353;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Patients'' furniture are in good condition', means_of_verification = 'Check that Patient beds are not rusted and are painted. Mattresses are clean and not torn
Trolleys, Stretchers, Wheel Chairs, etc. are well maintained( As applicable)' where id = 13354;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Furniture at the nursing station, staff room, administrative office are maintained', means_of_verification = 'Check  the condition of furniture at nursing station, duty room, office, etc. The furniture is not broken, painted/polished and clean.' where id = 13355;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'PHC has demarcated space for keeping condemned junk material', means_of_verification = 'Check for availability of a demarcated & secured space for collecting and storing the junk material before its disposal' where id = 13356;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'No junk material within the PHC premises', means_of_verification = 'Check if unused/ condemned articles, and outdated records are kept in the Nursing stations, OPD clinics, Labour Room , Injection Room , Dressing Room, Wards, stairs, open areas, roof tops, balcony etc.
No condemned vehicles are parked' where id = 13357;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'PHC has documented and implemented States'' Condemnation policy', means_of_verification = 'Check if PHC has drafted its condemnation policy or have got one from the state. Check whether it has been complied. ' where id = 13358;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'PHC has intact boundary wall and functional gates at entry', means_of_verification = 'Check that there is a proper boundary wall of adequate height without any breach. The Wall is painted in uniform colour' where id = 13359;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'PHC Infrastructure is well maintained', means_of_verification = 'No major cracks, seepage, chipped plaster & floors is seen within the building.
The Building is periodically maintained' where id = 13360;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'PHC has adequate facility for parking of vehicles', means_of_verification = 'Check that there is a demarcated space for parking of the vehicles as well as for the Ambulances and vehicles are parked systematically' where id = 13361;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Useful articles, records, drugs, etc. are arranged systematically', means_of_verification = 'Check if drugs, instruments, records, have been kept systematically near their usage points in demarcated areas. They are not lying in haphazard manner.' where id = 13362;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'The Staff periodically sorts useful and unnecessary articles at work stations', means_of_verification = 'Ask the staff about the frequency of  sorting and removal of unnecessary articles from their work place like Nursing stations, work bench, dispensing counter in Pharmacy, etc.
Check for presence of unnecessary articles.' where id = 13363;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Articles are labelled for easy recognition and easy retrieval.', means_of_verification = 'Check that drugs, instruments, records, etc. are labelled for facilitating easy identification.' where id = 13364;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Adequate illumination inside the building', means_of_verification = 'Check  for Adequate lighting arrangements through Natural Light or Electric Bulbs inside PHC' where id = 13365;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Adequate illumination in Outside of the PHC', means_of_verification = 'Check that PHC front, entry gate and access road are well illuminated' where id = 13366;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Use of energy efficient bulbs', means_of_verification = 'Check that PHC uses energy efficient bulb like CFL or LED for lighting purpose within the PHC Premises' where id = 13367;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'No dirt/Grease/Stains/ Cobwebs/Bird Nest/ Dust/ vegetation on the walls and roof in the PHC''s ward', means_of_verification = 'Check the floors and walls of wards for any visible or tangible dirt, grease, stains, etc.
Check the roof, walls, corners of wards for any Cobweb, Bird Nest, etc.' where id = 13368;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Wards are cleaned at least thrice in a day with wet mop', means_of_verification = 'Ask cleaning staff about frequency of cleaning in a day. Verify with the Housekeeping records' where id = 13369;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Surfaces are conducive for effective cleaning', means_of_verification = 'Check if surfaces are smooth for cleaning
  Check the floors and walls for cracks, uneven or any other defects which may adversely impact the cleaning procedure' where id = 13370;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Corridors are cleaned at least twice in a day with wet mop', means_of_verification = 'Ask cleaning staff about frequency of cleaning in a day. Verify with Housekeeping records.
  Corridors are rigorously cleaned with scrubbing / flooding once in a month' where id = 13371;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'No dirt/Grease/Stains/ Cobwebs/Bird Nest/ Dust/ vegetation on the walls and roof in the PHC''s circulation area', means_of_verification = 'Check that floors and walls of Corridors, Waiting area, stairs, roof top for any visible or tangible dirt, grease, stains, etc.
Check that roof, walls, corners of Corridors, Waiting area, stairs, roof top for any Cobweb, Bird Nest, etc.' where id = 13372;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Surfaces are conducive for effective cleaning', means_of_verification = 'Check if surfaces are smooth for cleaning
Check the floors and walls for cracks, uneven or any other defects which may adversely impact the cleaning procedure' where id = 13373;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Surfaces are conducive of effective cleaning', means_of_verification = 'Check if surfaces are smooth enough for cleaning check floors and walls for cracks, uneven or any other defects which may affect cleaning procedure' where id = 13374;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'No dirt/Grease/Stains and Cobwebs/Bird Nest/ Vegetation/ Dust on walls and roof in Auxiliary area', means_of_verification = 'Check that floors and walls of Pharmacy, Stores, Cold chain Room, Meeting Room etc. (As applicable) for any visible or tangible dirt, grease, stains, etc.
Check that roof, walls, corners of these area for any Cobweb, Bird Nest, etc.' where id = 13375;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Auxiliary areas are cleaned at least twice in a day with wet mop', means_of_verification = 'Ask cleaning staff about frequency of cleaning in a day. Verify with Housekeeping records
Areas are rigorously cleaned with scrubbing / flooding once in a month' where id = 13376;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Surfaces are conducive of effective cleaning', means_of_verification = 'Check if surfaces are smooth for ensuring cleaning
Check the floors and walls for cracks, uneven or any other defects which may affect cleaning procedure' where id = 13377;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Ambulatory and Diagnostic areas are cleaned at least twice in a day with wet mop', means_of_verification = 'Ask cleaning staff about frequency of cleaning in a day. Verify with Housekeeping records
' where id = 13378;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'No dirt/Grease/Stains and Cobwebs/Bird Nest/ Dust on walls and roof in Ambulatory & Diagnostic area', means_of_verification = 'Check that floors and walls of OPD, Lab, X-ray etc. (If available) for any visible or tangible dirt, grease, stains, etc.
Check that roof, walls, corners of these area for any Cobweb, Bird Nest, etc.' where id = 13379;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Availability of Cleaning Equipment', means_of_verification = 'Check the availability of mops, brooms, collection buckets etc. as per requirement. ' where id = 13380;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Availability of Detergent Disinfectant solution / Hospital Grade Phenyl for Cleaning purpose', means_of_verification = 'Check for good quality PHC cleaning solution preferably a ISI mark. Composition and concentration of solution is written on label.
Check with cleaning staff if they are getting adequate supply. Verify the consumption records.
Check, if the cleaning staff is aware of correct concentration and dilution method for preparing cleaning solution.' where id = 13381;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Availability of carbolic Acid/ Reputed compound (Aldehyde & other chemicals e.g. Bacillocid) for surface cleaning in procedure areas- Labour Room, OT (As Applicable)', means_of_verification = 'Check for adequacy of the supply. Verify with the records for stock-outs, if any' where id = 13382;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Use of Housekeeping Checklist', means_of_verification = 'Check that Housekeeping Checklist is displayed in PHC and updated. Check Housekeeping records if checklists are daily updated ' where id = 13383;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Periodic Monitoring of Housekeeping activities', means_of_verification = 'Periodic Monitoring is done by MOIC or another person designated. Please check record of such monitoring' where id = 13384;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Monitoring of adequacy and quality of material used for cleaning', means_of_verification = 'Check if there is any system of monitoring that adequate concentration of disinfectant solution is used for cleaning. PHC administration take feedback from cleaning staff about efficacy of the solution and take corrective action if required.' where id = 13385;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'No dirt/Grease/Stains/ Cobwebs/Bird Nest/ Dust/ vegetation on the walls and roof in the procedure area.', means_of_verification = 'Check that floors and walls of Procedure area like Labour Room, OT, Dressing Room, Immunization Room etc. (As Applicable) for any visible or tangible dirt, grease, stains, etc.
Check that roof, walls, corners of these area for any Cobweb, Bird-nest, vegetation, etc.' where id = 13386;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Surfaces are conducive for effective cleaning', means_of_verification = 'Check if surfaces are smooth for ensuring cleaning Check the floors and walls for cracks, uneven or any other defects which may affect cleaning procedure' where id = 13387;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Procedure area are cleaned at least twice in a day/ after every procedure (as applicable)', means_of_verification = 'Ask cleaning staff about frequency of cleaning in a day. Verify with Housekeeping records.
Areas are rigorously cleaned with scrubbing / flooding once in a week' where id = 13388;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Use of Three bucket system for cleaning', means_of_verification = 'Check if cleaning staff uses three bucket system for cleaning. (One bucket for Cleaning solution, second for plain water and third one for wringing the mop.) Ask the cleaning staff about the process. Disinfection and washing of mops after every cleaning cycle need to be undertaken.' where id = 13389;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Use unidirectional method and outward mopping', means_of_verification = 'Ask the cleaning staff to demonstrate, how they apply mop on floors. It should be in one direction without returning to the starting point. The mop should move from inner area to outer area of the room. Separate mop is used for the Procedure area.' where id = 13390;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'No use of brooms in patient care areas', means_of_verification = 'Check if brooms are stored in patient care areas. Ask cleaning staff if they use brooms for sweeping in wards, OT, Labour room. Brooms should not be used in patient care areas.' where id = 13391;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Availability of connection with Municipal Sewage System/ soak pit/ septic tank', means_of_verification = 'Check if PHC sewage has a connection with municipal system. If there is no access to municipal system, there should be septic tank. Check condition of septic tank e. g. Periodicity of cleaning, mosquito proofing of manhole, etc. ' where id = 13392;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Availability of closed drainage system with adequate gradient', means_of_verification = 'Check, PHC should have a closed drainage system or else drains should be properly covered.' where id = 13393;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'No blocked/ over-flowing drains in the facility', means_of_verification = 'Observe that the drains are not overflowing or blocked
All the drains are cleaned once in a week' where id = 13394;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'No dirt/Grease/Stains/ Garbage in Toilets', means_of_verification = 'Check some of the toilets randomly in indoor and outdoor areas for any visible dirt, grease, stains, water accumulation in toilets' where id = 13395;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'No foul smell in the Toilets and its dry', means_of_verification = 'Check some of the toilets randomly in indoor and outdoor areas for the foul smell and dryness of floor.' where id = 13396;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Toilets have running water and functional cistern', means_of_verification = 'Please operate cistern and water taps' where id = 13397;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Transportation of biomedical waste is done in closed container/trolley', means_of_verification = 'Check if transportation of waste from clinical areas to storage areas is done in covered trolleys / Bins. Trolleys used for patient shifting should not be used for transportation of waste.' where id = 13398;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'The facility has linkage with a CWTF Operator or has deep burial pit (with prior approval of the prescribed authority)', means_of_verification = 'Check record for functional linkage with a CWTF
In absence of such linkage, check existence of deep burial pit, which has approval of the prescribed authority.' where id = 13399;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Biomedical waste bins are covered', means_of_verification = 'Check that bins meant for bio medical waste are covered with a lid' where id = 13400;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Disinfection of Broken / Discarded Glassware is done as per recommended procedure', means_of_verification = 'Check if such waste is either pre-treated with 1-2%% Sodium Hypochlorite (having 30% residual chlorine) for 20 minutes or by autoclaving/ microwave/ hydroclave, followed storage in puncture proof  and leak proof boxes or containers with blue coloured marking  for re-cycling.' where id = 13401;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Staff is aware of needle stick injury Protocol', means_of_verification = 'Ask staff immediate management of exposure site; and Medical Officer knows criteria for PEP.
There should be functional linkage to DH / SDH/ CHC for PEP follow-up and check records of such referrals and follow-up' where id = 13402;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Sharp Waste is stored in Puncture proof containers', means_of_verification = 'Check availability of Puncture & leak proof container (White Translucent) at point of use for storing needles, syringes with fixed needles, needles from cutter/burner, scalpel blade, etc.' where id = 13403;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Dedicated Storage facility is available for biomedical waste', means_of_verification = 'Check if PHC has dedicated room for storage of Biomedical waste before disposal/handing over to Common Treatment Facility.' where id = 13404;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Access to waste storage facility is secured', means_of_verification = 'Observe the display of Biohazard symbol at storage areas
Check that the BMW storage is situated away from the main building and is kept under lock and key' where id = 13405;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'No Biomedical waste is stored for more than 48 Hours', means_of_verification = 'Verify that the waste is being disposed / handed over to CTF within 48 hour of generation. Check the record especially during holidays' where id = 13406;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Disposal of General Waste', means_of_verification = 'There is a mechanism of removal of general waste from the facility and its disposal.' where id = 13407;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Innovations in managing general waste', means_of_verification = 'Look for efforts of the health facility in managing General Waste, such as Recycling of paper waste, vermicomposting, waste to energy initiative, etc.' where id = 13408;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Availability of Compost pit as per specification', means_of_verification = 'Availability of compost pit for Bio degradable general waste. ' where id = 13409;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Availability of Needle/ Hub cutter and puncture proof boxes', means_of_verification = 'At each point of generation of sharp waste' where id = 13410;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Availability of Colour coded liners for Biomedical waste and general waste', means_of_verification = 'Check all the bins are provided with chlorine free liners. Ask staff about adequacy of supply.' where id = 13411;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Availability of Bins for segregated collection of waste at point of use', means_of_verification = 'One set of bins of appropriate size at each point of generation for Biomedical and General waste.' where id = 13412;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Check if the staff is aware of segregation protocol', means_of_verification = 'Ask staff about the segregation protocol.' where id = 13413;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Display of work instructions for segregation and handling of Biomedical waste', means_of_verification = 'Check for instructions for segregation of waste in different  colour coded bins are displayed at point of use.' where id = 13414;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Segregation of BMW is done as per BMW management rule,2016', means_of_verification = 'Anatomical waste and soiled dressing material are segregated in Yellow Bin
General and infectious waste are not mixed                                                                                                                          ' where id = 13415;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'PHC has adequate facility for disposal of Biomedical waste', means_of_verification = 'The Health facility within 75 KM of CTF shall have a valid contract with a Common Treatment facility for disposal of Bio medical waste. Or else facility should have Deep Burial Pit and Sharp Pit within premises of Health facility. Such deep burial pit should have approval of the Prescribed Authority' where id = 13416;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Facility manages recyclable waste as per approved procedure', means_of_verification = 'Check management of IV Bottles (Plastic), IV tubes, Urine Bags, Syringes, Catheter, etc.
(Autoclaving/ Microwaving/ Hydroclaving followed by shredding or a combination of sterilisation and shredding. Later treated waste is handed over to registered vendors.)' where id = 13417;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Deep Burial Pit is constructed as per norms given in the Biomedical Waste Rules 2016', means_of_verification = 'Located away from the main PHC building and water source, A pit or trench should be dug about two meters deep. It should be half filled with waste, then covered with lime within 50 cm of the surface, before filling the rest of the pit with soil.
Secured from animals . If waste disposed through CTF, then a deep burial pit is not required.(Give Full Compliance)' where id = 13418;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'PHC maintains records, as required under the Biomedical Waste Rules 2016', means_of_verification = 'Check following records -
a. Yearly Health Check-up record of all handlers
b. BMW training records of all staff (once in year training)
c. Immunisation records of all waste handlers' where id = 13419;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'PHC has a valid authorization for Bio Medical waste Management from the prescribed authority', means_of_verification = 'Check for the validity of authorization certificate' where id = 13420;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'PHC submits Annual report to pollution control board', means_of_verification = 'Check the records that reports have been submitted to the prescribed authority on or before 30th June every year. ' where id = 13421;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Disposal of Expired or discarded medicine', means_of_verification = 'Returned back to manufacturer or supplier
Alternatively handed over to CWTF Operator for incineration at temperature > 12000C' where id = 13422;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Availability of Mercury Spill Management Kit and Staff is aware of Mercury Spill management', means_of_verification = 'Check for Mercury Spill Management Kit and ask staff what he/she would do in case of Mercury spill. (If facility is mercury free give full compliance)' where id = 13423;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Disposal of used Disinfectant solution like Glutaraldehyde', means_of_verification = 'System of pre-treatment before ' where id = 13424;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Hand-washing facilities have been provided for patients, handing-over Urine Samples', means_of_verification = 'Check the availability of effluent treatment system.' where id = 13425;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Liquid waste is made safe before mixing with other waste water', means_of_verification = 'Check for the procedure - staff interview and direct observation' where id = 13426;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'The laboratory has a functional protocol for managing discarded samples', means_of_verification = 'A copy of such protocol should be available and staff should be aware of the same. ' where id = 13427;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Facility measures the Health care associated infections', means_of_verification = 'Check for monitoring of Healthcare Associated Infection that may occur in a Primary healthcare setting like Injection abscess, Postpartum sepsis, infection at dressing and suturing sites etc.' where id = 13428;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Regular Monitoring of infection control practices', means_of_verification = 'Check, if there is any practice of daily monitoring of infection control practice like hand hygiene and personal protection' where id = 13429;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Facility reports all notifiable diseases and events', means_of_verification = 'Check that the facility has list of all notifiable disease needs immediate/periodic reporting to higher authority.
Check records that notifiable disease have been reported in program such as IDSP and AEFI Surveillance.' where id = 13430;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Availability of Sink and running water at point of use', means_of_verification = 'Check for washbasin with functional tap, soap and running water at all points of use' where id = 13431;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Display of Hand washing Instructions', means_of_verification = 'Check that Hand washing instructions are displayed preferably at all points of use' where id = 13432;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Staff is aware of standard hand washing protocol', means_of_verification = 'Ask facility staff to demonstrate 6 steps of normal hand wash and 5 moments of hand washing' where id = 13433;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Correct method of wearing and removing PPEs', means_of_verification = 'Ask the staff to demonstrate correct method of wearing and removing Gloves, caps and masks etc.' where id = 13434;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'The staff is aware of use of gloves, when to use (occasion) and its type', means_of_verification = 'Check with the staff when do they wear gloves, and when gloves are not required. The Staff should also know difference between clean & sterilized gloves and when to use' where id = 13435;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'No re-use of disposable personal protective equipment', means_of_verification = 'Check that disposable gloves and mask are not re-used. Reusable Gloves and mask are used after adequate sterilization.' where id = 13436;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Decontamination and cleaning of instruments after use', means_of_verification = 'Check whether instruments are decontaminated with 0.5% chlorine solution for 10 minutes.  Check instruments are cleaned thoroughly with water and soap before sterilization' where id = 13437;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Decontamination of operating and Surface examination table, dressing tables etc. after every procedures', means_of_verification = 'Ask staff  when and how they clean the operating surfaces either by chlorine solution or Disinfectant like carbolic acid' where id = 13438;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Staff knows how to make Chlorine solution', means_of_verification = 'Ask the staff how to make 1% chlorine solution from Bleaching powder and Hypochlorite solution' where id = 13439;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Infectious patients are not mixed for general patients', means_of_verification = 'Check infectious patients are  separated from other patients ' where id = 13440;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Restriction of external foot wear in critical areas', means_of_verification = 'External foot wear are not allowed in labour room, OT etc.( As Applicable)' where id = 13441;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Maintenance of adequate bed to bed distance in wards', means_of_verification = 'A distance of 3.5 Foot is maintained between two beds in wards' where id = 13442;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Use of Heavy Duty Gloves and gumboot by waste handlers', means_of_verification = 'Check, if the housekeeping staff and waste handlers are using heavy duty gloves and gum boots' where id = 13443;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Use of Gloves during procedures and examination', means_of_verification = 'Check, if the staff uses gloves during examination, and while conducting procedures' where id = 13444;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Use of Masks ,Head cap and Lab coat, Apron etc.', means_of_verification = 'Check, if staff uses mask head caps , Lab coat and aprons in patient care and procedure areas' where id = 13445;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Antibiotic Policy is implemented at the facility', means_of_verification = 'Check if the PHC has documented Anti biotic policy and doctors are aware of it.' where id = 13446;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Infection Control Committee is constituted and functional in the PHC', means_of_verification = 'Check for the enabling order and minutes of the meeting' where id = 13447;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Immunization and medical check-up of Service Providers', means_of_verification = 'PHC staff has been immunized against Hepatitis B
Check for the records and lab investigations of staff' where id = 13448;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Spill management protocols are displayed at points if use', means_of_verification = 'Check for display' where id = 13449;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Availability of spill management Kit', means_of_verification = 'Check availability of kits' where id = 13450;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Staff is aware of how to manage spills', means_of_verification = 'Check for adherence to protocols' where id = 13451;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Preventive measures for air borne infections has been taken', means_of_verification = 'Check staff is aware, adhere and promote respiratory hygiene and cough etiquettes' where id = 13452;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Adequate number of Air-exchange in Laboratory', means_of_verification = 'Please check availability and serviceability of exhaust fan in the laboratory' where id = 13453;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Cross-ventilation at Patient Care areas (ward, labour room and dressing room)', means_of_verification = 'Check availability of  Fans/ air conditioning/ Heating/ exhaust/ Ventilators as per environment condition and requirement' where id = 13454;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Adherence to Protocols for sterilization', means_of_verification = 'Check about awareness of recommended temperature, duration and pressure for autoclaving instruments - 121 degree C, 15 Pound Pressure for 20 Minutes (30 Minutes if wrapped) Linen - 121 C, 15 Pound for 30 Minutes.
Check if the staff know the protocol for sterilization of laparoscope soaking it in 2% Glutaraldehyde solution for 10 Hours' where id = 13455;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Adherence to Protocol for High Level disinfection', means_of_verification = 'Check with the staff process about of High Level disinfection using Boiling for 20 minutes with lid on, soaking in 2% Glutaraldehyde/Chlorine solution for 20 minutes.' where id = 13456;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Use of autoclave tape for monitoring of sterilization', means_of_verification = 'Check autoclaving records for use of sterilization indicators (signal Lock)' where id = 13457;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Cold storage equipment''s are clean and managed properly', means_of_verification = 'Check ILR, Deep freezers and Ice packs are clean
Check there is a practice of regular cleaning.
Check vaccines are kept in sequence
Check work instruction for storage of vaccines are displayed at point of use

' where id = 13458;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Cold storage equipment are not used for storing other items, than vaccine .', means_of_verification = 'Check eatables are not kept in ILR/Deep Freezers' where id = 13459;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Medicines are arranged systematically', means_of_verification = 'Check all the shelves/racks containing medicines  are labelled in  pharmacy and drug store
Heavy items are stored at lower shelves/racks
Fragile items are not stored at the edges of the shelves
Drugs and consumables are stored away from water and sources of  heat, direct sunlight etc.
Drugs are not stored at floor and adjacent to wall


' where id = 13460;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Drinking Water is tested and chlorinated', means_of_verification = 'Presence of free chlorine at 0.2 ppm is tested in the samples drawn at the consumer''s end.' where id = 13461;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = TRUE, am_record_review = TRUE, name = 'The facility receives adequate quantity of water as per requirement', means_of_verification = 'At least 200 litres of water per bed per day is available (if municipal supply). or the water is available on 24x7 basis at all points of usage' where id = 13462;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'There is storage tank for the water and tank is cleaned periodically', means_of_verification = 'The PHC should have capacity to store 48 hours water requirement Water tank is cleaned at six monthly interval and records are maintained.' where id = 13463;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Bed-sheets and pillow cover are stain free and clean', means_of_verification = 'Observe the condition of linen in use in the wards and other patient care area' where id = 13464;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'The facility has adequate stock (including reserve) of linen', means_of_verification = 'Check the stock position and its turn-over during last one year in term of demand and availability' where id = 13465;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = TRUE, am_record_review = FALSE, name = 'Bed-sheets and linen are changed daily', means_of_verification = 'Check, if the bedsheets and pillow cover have been changed daily. Please interview the patients as well.' where id = 13466;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Medical officers monitor cleanliness and hygiene of outreach sessions and sub centres.', means_of_verification = 'Check with medical officers and records of monthly meeting ''Swachh Baharat Abhiyan'' has been followed up during monthly meetings with extension workers like MPW, ASHA, ANM etc.' where id = 13467;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'ASHA''s are promoting cleanliness and hygiene practices', means_of_verification = 'Check for ASHA''s counsel mothers for hand hygiene, toilets, water sanitation etc.' where id = 13468;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Biomedical waste generated during outreach session are transported to the PHC on the same day', means_of_verification = 'Check the records and ask staff' where id = 13469;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Security personal reprimands attendants, who found indulging into unhygienic behaviour - spitting, open field urination & defecation, etc.', means_of_verification = 'Check, if security personnel watch behaviour of patients and their attendants, particularly in respect of hygiene, sanitation, etc. and take appropriate actions, as deemed.' where id = 13470;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Departments are locked after working hours', means_of_verification = 'Departments like OPD, Lab, Administrative office etc. are locked after working hours.' where id = 13471;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'One Security Guard per shift', means_of_verification = 'Check for the presence of one security personnel at PHC every shift' where id = 13472;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Bio medical waste Management training has been provided to the staff', means_of_verification = 'Verify with the training records' where id = 13473;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'PHC has documented Standard Operating procedures for Cleanliness, Bio-Medical waste management and Infection Control', means_of_verification = 'Check availability of SOP with respective users' where id = 13474;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Infection control Training has been provided to the staff', means_of_verification = 'Check staff are trained at the time of induction and once in every year' where id = 13475;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Cleanliness and infection control committee has representation of all cadre of staff including Group ‘D’ and cleanings staff', means_of_verification = 'Verify with the records' where id = 13476;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Roles and responsibility of different staff members have been assigned and communicated', means_of_verification = 'Ask different members about their roles and responsibilities' where id = 13477;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'PHC leadership review the progress of the cleanliness drive on weekly basis', means_of_verification = 'Check about regularity of meetings and monitoring activities regarding cleanliness drive' where id = 13478;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'The Health facility has a system to take feed-back from patients and visitors for maintaining the cleanliness of the facility', means_of_verification = 'Check if there is a feedback system for the patients. Verify the records' where id = 13479;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Local community and organisations are involved in monitoring and promoting cleanliness', means_of_verification = 'Members of RKS and Local Governance bodies monitor the cleanliness of the PHC at pre-defined intervals
Local NGO/ Civil Society Organizations/Panchayati Raj Institution are involved in cleanliness of the PHC' where id = 13480;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = TRUE, am_record_review = FALSE, name = 'Patients are made aware of their responsibility of keeping the health facility clean', means_of_verification = 'Ask patients about their roles& responsibilities with regards to cleanliness. Patient’s responsibilities should be prominently displayed' where id = 13481;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'IEC regarding importance of maintaining hand hygiene is displayed in PHC premises', means_of_verification = 'Should be displayed prominently in local language' where id = 13482;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'IEC regarding use of toilets is displayed within PHC premises', means_of_verification = 'Should be displayed prominently in local language' where id = 13483;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'IEC regarding Swachhta Abhiyan is displayed within the facilities’ premises', means_of_verification = 'Should be displayed prominently in local language' where id = 13484;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'PHC has dress code policy for all cadre of staff', means_of_verification = 'PHCs staff adhere to dress code' where id = 13485;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'There is a regular monitoring of hygiene of staff', means_of_verification = 'Check about personal hygiene and clean dress of staff' where id = 13486;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Identity cards and name plates have been provided to all staff', means_of_verification = 'Check staff uses I Card and name plate' where id = 13487;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Parks and green areas in the surrounding area are well maintained', means_of_verification = 'Check that there no wild vegetation & growth in the surroundings. Shrubs and trees are well maintained.  Dry leaves and green waste are removed regularly.' where id = 15107;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'No loose hanging wires in and around bill boards, electrical polls etc.', means_of_verification = 'Check for any loose hanging wires' where id = 15108;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Illumination in surrounding area', means_of_verification = 'Check that hospital front, approach road and surrounding area are well illuminated with street lights' where id = 15109;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'No unwanted/broken/torn/ loose hanging posters/billboards.', means_of_verification = 'Check that hospital surrounding are not studded with irrelevant and out dated posters, slogans, wall writings, graffiti, etc.' where id = 15110;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'There are no stray animals in surrounding area', means_of_verification = 'Observe for the presence of stray animals such as pigs, dogs cattle, etc.' where id = 15111;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'All drains/sewer are covered.', means_of_verification = 'Check for open manhole and overflowing drains.' where id = 15112;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Approach road are even and free from pot-holes', means_of_verification = 'Check that approach roads are clean and free from  pot-holes and water stagnation' where id = 15113;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'On the way signages are available', means_of_verification = 'Check for directional signage with name of the facility on the approach road.' where id = 15114;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Area around the facility is clean, neat and tidy', means_of_verification = 'Check for any litter/garbage/ in the surrounding area of the facility.' where id = 15115;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Functional street lights are available on the approach road', means_of_verification = 'Check for street lights and their functionality. ' where id = 15116;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Surrounding areas are well maintained', means_of_verification = 'Check that there is no over grown shrubs, weeds, grass, potholes, bumps etc. in surrounding areas' where id = 15117;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Innovations in managing waste', means_of_verification = 'Check, if certain innovative practices have been introduced for managing waste e.g. Vermicomposting/Re-cycling of papers/Waste to energy/Compost Activators, etc.' where id = 15118;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Availability of bins for General recyclable and biodegradable wastes', means_of_verification = 'Check availability adequate number of bins for Biodegradable and recyclable general waste in the nearby market' where id = 15119;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Availability of garbage storage area/ compost pit', means_of_verification = 'Garbage storage area is away from residential/commercial areas and is covered/ fenced. It is not causing public nuisance. In rural set-up there should be a compost pit.' where id = 15120;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Regular repairs and maintained of roads, footpaths and pavements', means_of_verification = 'Check when was the last repair done and current condition of the road- pot-holes, broken footpath etc.' where id = 15121;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Vendors & hawkers have designated place outside the facility', means_of_verification = 'Check for the availability of designated place for vendors & hawkers and cleanliness' where id = 15122;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Such toilets/Urinal are neat & clean', means_of_verification = 'Check availability of water and level of cleanliness' where id = 15123;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Availability of adequate parking facilities for Public Transport such as Cycle Rickshaw, Tanga, Auto, Taxi', means_of_verification = 'Check signage & parking space: Also check that such transports are parked haphazardly' where id = 15124;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Presence of Safe Drinking Water facility outside the boundary wall', means_of_verification = 'Check for its presence and functionality' where id = 15125;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = FALSE, am_patient_interview = FALSE, am_record_review = FALSE, name = 'Availability of Public toilets/ Urinal in surrounding Area', means_of_verification = 'Check for availability separate toilets/ Urinal for male and female ' where id = 15126;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'The Facility coordinates with local Gram Panchayat/Urban local bodies and NGOs for improving Swachhata in vicinity of the health facility', means_of_verification = 'Look for evidence of collective action such as cleaning of drains, maintenance of parking space, orderly arrangement of hawkers (outside the facility), rickshaw, auto, taxi, construction & maintenance of public toilets, improving street-lighting, removing cattle nuisance, etc.' where id = 15127;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Facility coordinates with other departments for improving Swachhata', means_of_verification = 'Look for evidence of coordination with departments such as Education (school programs on hygiene promotions), Water and Sanitation (making area ODF), PWD (Repair & Maintenance), Forest Department (Plantation Drive) etc., which contributes strengthening towards of hygiene & sanitation' where id = 15128;
update checkpoint set last_modified_date = current_timestamp, am_observation = TRUE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Implementation of IEC activities related to '' Swachh Bharat Abhiyan''', means_of_verification = 'Advertisement in news-papers/electronic media, distribution of booklets/ pamphlets, posters/wall writing-promoting use of toilets, hand washing, safe drinking water and tree plantation, etc. ' where id = 15129;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Local community actively participates during Swachhata Pakhwara(Fortnight)', means_of_verification = 'Local community is actively involved in administration of ''Swachhata Pledge'' and distribution of caps/T-shirts, badge with cleanliness message and logos of ''Swachh Bharat Abhiyan'' and ''Kayakalp''.' where id = 15130;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Community awareness by organising cultural programme and competitions', means_of_verification = 'Like  rally/marathon/ Swachhata walk/human chain, street plays, essay/ poem/slogan/painting competition, etc.' where id = 15131;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Surrounding area is declared Open Defecation Free', means_of_verification = 'Check block/Ward is declared ODF' where id = 15132;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'The Facility has undertaken initiative for community mobilization in the surrounding for improving Swachhata', means_of_verification = 'Check for any mobilization activities in line with VISHWAS campaign initiated by MoHFW, involving VHSNC/MAS ' where id = 15133;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'The Facility endeavours to attract financial support from other organisations', means_of_verification = 'Look for evidence that the health facility has been supported by other organisations such as Industry, Business houses, NGOs, Rotary & Lions clubs, market associations, welfare associations etc. for improving the cleanliness in the surroundings' where id = 15134;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'The facility engages the local Community for reducing household pollutions in the vicinity', means_of_verification = 'Look for evidence that the facility has engaged in reducing household level pollution in near vicinity of the health facility – Presence of community bins for segregated collection of general (biodegradable & recyclable), Compost-pits, Roll-out of PM Ujjwala Scheme in nearby slum, etc. ' where id = 15135;
update checkpoint set last_modified_date = current_timestamp, am_observation = FALSE, am_staff_interview = TRUE, am_patient_interview = FALSE, am_record_review = TRUE, name = 'Facility endeavours to attract financial support from local support', means_of_verification = 'Look for evidence that local MPs/MLAs/Municipal Councillors/Panchayat Members/Zila Parisad/ individual donations have supported health facility in its cleanliness efforts.' where id = 15136;
