update indicator_definition set name = '52. Current Labour Room Quality Score', sort_order=4900, last_modified_date = current_timestamp where name = '41. Current Labour Room Quality Score';
update indicator_definition set name = '53. Current Maternity OT Quality Score', sort_order=5000, last_modified_date = current_timestamp where name = '42. Current Maternity OT Quality Score';
update indicator_definition set name = '54. Current OSCE Score', sort_order=5100, last_modified_date = current_timestamp where name = '43. Current OSCE Score';
update indicator_definition set symbol = 'numberOfLiveBirths', last_modified_date = current_timestamp where name = '10. Total number of live births';
update indicator_definition set symbol = 'numberOfCSectionDeliveries', last_modified_date = current_timestamp where name = '7(c). Total number of C-Sections';

insert into indicator_definition (name, data_type, assessment_tool_id, symbol, description, sort_order, output) VALUES ('41a. No. of deliveries done at Night', 'Numeric', (select id from assessment_tool where name = 'LAQSHYA Monthly'), 'numberOfDeliveriesAtNight', 'LR Register', 3700, false);
insert into indicator_definition (name, data_type, assessment_tool_id, formula, description, sort_order, output) VALUES ('41. Percentage of deliveries conducted at night', 'Percentage', (select id from assessment_tool where name = 'LAQSHYA Monthly'), '(numberOfDeliveriesAtNight * 100/(numberOfVaginalDeliveries + numberOfAssistedVaginalDeliveries + numberOfCSectionDeliveries))', '', 3710, false);
insert into indicator_definition (name, data_type, assessment_tool_id, symbol, description, sort_order, output) VALUES ('42a. No. of C-sections done at Night', 'Numeric', (select id from assessment_tool where name = 'LAQSHYA Monthly'), 'numberOfCSectionDeliveriesAtNight', 'OT Register', 3800, false);
insert into indicator_definition (name, data_type, assessment_tool_id, formula, description, sort_order, output) VALUES ('42. Percentage of C - section conducted at night', 'Percentage', (select id from assessment_tool where name = 'LAQSHYA Monthly'), '((numberOfCSectionDeliveriesAtNight * 100)/(numberOfVaginalDeliveries + numberOfAssistedVaginalDeliveries + numberOfCSectionDeliveries))', '', 3810, false);
insert into indicator_definition (name, data_type, assessment_tool_id, symbol, description, sort_order, output) VALUES ('43a. No. of elective C-sections', 'Numeric', (select id from assessment_tool where name = 'LAQSHYA Monthly'), 'numberOfElectiveCSections', 'OT Register', 3900, false);
insert into indicator_definition (name, data_type, assessment_tool_id, formula, description, sort_order, output) VALUES ('43. Percentage of elective C - section ', 'Percentage', (select id from assessment_tool where name = 'LAQSHYA Monthly'), '((numberOfElectiveCSections * 100)/(numberOfVaginalDeliveries + numberOfAssistedVaginalDeliveries + numberOfCSectionDeliveries))', '', 3910, false);
insert into indicator_definition (name, data_type, assessment_tool_id, symbol, description, sort_order, output) VALUES ('44a. No. of babies required resuscitation', 'Numeric', (select id from assessment_tool where name = 'LAQSHYA Monthly'), 'numberOfBabiesRequiredResuscitation', 'LR register', 4000, false);
insert into indicator_definition (name, data_type, assessment_tool_id, formula, description, sort_order, output) VALUES ('44. Percentage of newborn required resuscitation out of total live birth', 'Percentage', (select id from assessment_tool where name = 'LAQSHYA Monthly'), '((numberOfBabiesRequiredResuscitation * 100)/numberOfLiveBirths)', '', 4010, false);
insert into indicator_definition (name, data_type, assessment_tool_id, symbol, description, sort_order, output) VALUES ('45a. No of cases referred out to OT', 'Numeric', (select id from assessment_tool where name = 'LAQSHYA Monthly'), 'numberOfCasesReferredToOT', 'LR register', 4100, false);
insert into indicator_definition (name, data_type, assessment_tool_id, symbol, description, sort_order, output) VALUES ('45b. Total no. of admission in the labour room', 'Numeric', (select id from assessment_tool where name = 'LAQSHYA Monthly'), 'numberOfAdmissionsInLabourRoom', 'LR register', 4101, false);
insert into indicator_definition (name, data_type, assessment_tool_id, formula, description, sort_order, output) VALUES ('45. Percentage of cases referred to Maternity OT', 'Percentage', (select id from assessment_tool where name = 'LAQSHYA Monthly'), '((numberOfCasesReferredToOT * 100)/numberOfAdmissionsInLabourRoom)', '', 4110, false);
insert into indicator_definition (name, data_type, assessment_tool_id, symbol, description, sort_order, output) VALUES ('46a. Total no. of Obstetric Complications Managed ', 'Numeric', (select id from assessment_tool where name = 'LAQSHYA Monthly'), 'numberOfObstetricComplicationsManaged', 'LR Register', 4300, false);
insert into indicator_definition (name, data_type, assessment_tool_id, formula, description, sort_order, output) VALUES ('46. Percentage of complicated cases managed', 'Percentage', (select id from assessment_tool where name = 'LAQSHYA Monthly'), '((numberOfObstetricComplicationsManaged * 100)/numberOfAdmissionsInLabourRoom)', '', 4310, false);
insert into indicator_definition (name, data_type, assessment_tool_id, symbol, description, sort_order, output) VALUES ('47a. Total no. of PPIUCD inserted', 'Numeric', (select id from assessment_tool where name = 'LAQSHYA Monthly'), 'numberOfPPIUCDInserted', 'LR Register', 4400, false);
insert into indicator_definition (name, data_type, assessment_tool_id, formula, description, sort_order, output) VALUES ('47. Percentage PPIUCD inserted against total number of deliveries', 'Percentage', (select id from assessment_tool where name = 'LAQSHYA Monthly'), '(numberOfPPIUCDInserted * 100/(numberOfVaginalDeliveries + numberOfAssistedVaginalDeliveries + numberOfCSectionDeliveries))', '', 4410, false);
insert into indicator_definition (name, data_type, assessment_tool_id, symbol, description, sort_order, output) VALUES ('48a. Number of cancelled C-section', 'Numeric', (select id from assessment_tool where name = 'LAQSHYA Monthly'), 'numberOfCancelledCSection', 'OT Register', 4500, false);
insert into indicator_definition (name, data_type, assessment_tool_id, formula, description, sort_order, output) VALUES ('48. Operation cancellation rate', 'Percentage', (select id from assessment_tool where name = 'LAQSHYA Monthly'), '((numberOfCancelledCSection * 100)/numberOfCSectionDeliveries)', '', 4510, false);
insert into indicator_definition (name, data_type, assessment_tool_id, symbol, description, sort_order, output) VALUES ('49a. No of Perioperative deaths in OT during C-Section', 'Numeric', (select id from assessment_tool where name = 'LAQSHYA Monthly'), 'numberOfPerioperativeDeathsInOTDuringCSection', 'OT Register', 4600, false);
insert into indicator_definition (name, data_type, assessment_tool_id, formula, description, sort_order, output) VALUES ('49. Perioperative death rate', 'Percentage', (select id from assessment_tool where name = 'LAQSHYA Monthly'), '((numberOfPerioperativeDeathsInOTDuringCSection * 100)/numberOfCSectionDeliveries)', '', 4610, false);
insert into indicator_definition (name, data_type, assessment_tool_id, symbol, description, sort_order, output) VALUES ('50a. Total no. of adverse event cases in Labour Room', 'Numeric', (select id from assessment_tool where name = 'LAQSHYA Monthly'), 'numberOfAdverseEventCasesInLabourRoom', 'Adverse event register', 4700, false);
insert into indicator_definition (name, data_type, assessment_tool_id, formula, description, sort_order, output) VALUES ('50. Number of adverse event per 1000 patient', 'Numeric', (select id from assessment_tool where name = 'LAQSHYA Monthly'), '((numberOfAdverseEventCasesInLabourRoom * 1000)/numberOfAdmissionsInLabourRoom)', '', 4710, false);
insert into indicator_definition (name, data_type, assessment_tool_id, symbol, description, sort_order, output) VALUES ('51. Downtime critical equipment in LR & OT', 'Numeric', (select id from assessment_tool where name = 'LAQSHYA Monthly'), 'numberOfBreakdownDaysForOT', 'Equipment maintenance register', 4800, false);


-- NEW AT
update assessment_tool set sort_order = 40 where name = 'NQAS';
update assessment_tool set sort_order = 30 where name = 'LAQSHYA Baseline';
update assessment_tool set sort_order = 20 where name = 'LAQSHYA Monthly';
insert into assessment_tool (name, assessment_tool_mode_id, type, sort_order) values ('Annexure C', (select id from assessment_tool_mode where name = 'LAQSHYA'), 'INDICATOR', 10);
insert into indicator_definition (name, data_type, assessment_tool_id, sort_order, output) values ('Date of entry', 'Date', (select id from assessment_tool where name = 'Annexure C'), 100, false);

insert into indicator_definition (name, data_type, assessment_tool_id, description, sort_order, output, coded_values) VALUES ('1. Facility has assessed Labour Room and OT using NQAS checklist and reported Baseline Quality Scores ', 'Coded', (select id from assessment_tool where name = 'Annexure C'), '', 200, false, '["Yes", "No"]');
insert into indicator_definition (name, data_type, assessment_tool_id, description, sort_order, output, coded_values) VALUES ('2. Facility has set Quality Team at facility level and Quality Circles in Labour Room & Maternity Ots', 'Coded', (select id from assessment_tool where name = 'Annexure C'), '', 300, false, '["Yes", "No"]');
insert into indicator_definition (name, data_type, assessment_tool_id, description, sort_order, output, coded_values) VALUES ('3. Facility has oriented the Labour room and Maternity OT staff on LR protocols, RMC & QI', 'Coded', (select id from assessment_tool where name = 'Annexure C'), '', 400, false, '["Yes", "No"]');
insert into indicator_definition (name, data_type, assessment_tool_id, description, sort_order, output) VALUES ('4. Percentage of deliveries  attended by a birth companion', 'Numeric', (select id from assessment_tool where name = 'Annexure C'), '', 500, false);
insert into indicator_definition (name, data_type, assessment_tool_id, description, sort_order, output) VALUES ('5a. Percentage deliveries are conducted using safe birth checklist in Labour Room ', 'Numeric', (select id from assessment_tool where name = 'Annexure C'), 'At least 90% deliveries are conducted using safe birth  checklist in Labour Room', 600, false);
insert into indicator_definition (name, data_type, assessment_tool_id, description, sort_order, output) VALUES ('5b. Percentage of deliveries are conducted using  Safe Surgery checklist in Maternity OT', 'Numeric', (select id from assessment_tool where name = 'Annexure C'), 'At least 90% deliveries are conducted using  Safe Surgery checklist in  Maternity OT', 610, false);
insert into indicator_definition (name, data_type, assessment_tool_id, description, sort_order, output) VALUES ('6. Percentage of deliveries for which Partograph is generated using real-time information in at least ', 'Numeric', (select id from assessment_tool where name = 'Annexure C'), 'Partograph is generated using real-time information in at least 90% deliveries in Labour Rooms', 700, false);
insert into indicator_definition (name, data_type, assessment_tool_id, description, sort_order, output) VALUES ('7. Percentage breastfeeding within 1 hour ', 'Numeric', (select id from assessment_tool where name = 'Annexure C'), 'Achieved 80%  or more  breastfeeding within 1 hour or at least 30% increment from the baseline', 800, false);
insert into indicator_definition (name, data_type, assessment_tool_id, description, sort_order, output) VALUES ('8.  Neonatal asphyxia rate in Inborn Babies ', 'Numeric', (select id from assessment_tool where name = 'Annexure C'), 'Achieved 0%  neonatal asphyxia rate in Labour Roomor at least reduction of 20%  from baseline', 900, false);
insert into indicator_definition (name, data_type, assessment_tool_id, description, sort_order, output) VALUES ('9.  Neonatal sepsis rate in-born babies ', 'Numeric', (select id from assessment_tool where name = 'Annexure C'), 'Achieved 0%  neonatal sepsis rate in-born babies or at least reduction of 20%  from baseline', 1000, false);
insert into indicator_definition (name, data_type, assessment_tool_id, description, sort_order, output) VALUES ('10.  Surgical Site infection Rate in Maternity OT ', 'Numeric', (select id from assessment_tool where name = 'Annexure C'), 'Achieved 5% or less Surgical Site infection Rate in Maternity OT or at least reduction of 30%  from baseline', 1100, false);
insert into indicator_definition (name, data_type, assessment_tool_id, description, sort_order, output) VALUES ('11. Antenatal corticosteroid administration rate in case in preterm labour', 'Numeric', (select id from assessment_tool where name = 'Annexure C'), 'Achieved 80% or more antenatal corticosteroid administration rate in case in preterm labour or at least increment of 30%  from baseline', 1200, false);
insert into indicator_definition (name, data_type, assessment_tool_id, description, sort_order, output) VALUES ('12. Pre-eclampsia, eclampsia & PIH related mortality', 'Numeric', (select id from assessment_tool where name = 'Annexure C'), 'No case of pre-eclampsia, eclampsia & PIH related mortality or at least 25% reduction from the baseline', 1300, false);
insert into indicator_definition (name, data_type, assessment_tool_id, description, sort_order, output) VALUES ('13.  APH/PPH related mortality ', 'Numeric', (select id from assessment_tool where name = 'Annexure C'), 'No case of APH/PPH related mortality or at least 25% reduction from the baseline', 1400, false);
insert into indicator_definition (name, data_type, assessment_tool_id, description, sort_order, output, coded_values) VALUES ('14. Facility Labour Room is reorganized as labour room standardization guidelines', 'Coded', (select id from assessment_tool where name = 'Annexure C'), '', 1500, false, '["In Progress", "Yes", "No"]');
insert into indicator_definition (name, data_type, assessment_tool_id, description, sort_order, output, coded_values) VALUES ('15. Facility Labour room has staffing as per defined norms ', 'Coded', (select id from assessment_tool where name = 'Annexure C'), 'Facility Labour room has staffing as per defined norms in annexure B', 1600, false, '["Yes", "No"]');
insert into indicator_definition (name, data_type, assessment_tool_id, description, sort_order, output) VALUES ('16. Percentage of Women, administered Oxytocin, immediately after birth.', 'Numeric', (select id from assessment_tool where name = 'Annexure C'), '100% of Women, administered Oxytocin, immediately after birth.', 1700, false);
insert into indicator_definition (name, data_type, assessment_tool_id, description, sort_order, output) VALUES ('17. OSCE Score ', 'Numeric', (select id from assessment_tool where name = 'Annexure C'), '80% and more OSCE scores or at least increment of 30% from baseline', 1800, false);
insert into indicator_definition (name, data_type, assessment_tool_id, description, sort_order, output, coded_values) VALUES ('18. Facility conducts referral audit on Monthly basis', 'Coded', (select id from assessment_tool where name = 'Annexure C'), '', 1900, false, '["Yes", "No"]');
insert into indicator_definition (name, data_type, assessment_tool_id, description, sort_order, output, coded_values) VALUES ('19. Facility conducts Maternal death, Neonatal death and near-miss on monthly basis', 'Coded', (select id from assessment_tool where name = 'Annexure C'), '', 2000, false, '["Yes", "No"]');
insert into indicator_definition (name, data_type, assessment_tool_id, description, sort_order, output, coded_values) VALUES ('20. Facility report zero stock outs in Labour Room & Maternity OT', 'Coded', (select id from assessment_tool where name = 'Annexure C'), '', 2100, false, '["Yes", "No"]');
insert into indicator_definition (name, data_type, assessment_tool_id, description, sort_order, output) VALUES ('21. Percentage of beneficiaries  who were either satisfied or highly satisfied', 'Numeric', (select id from assessment_tool where name = 'Annexure C'), '80% of the beneficiaries are either satisfied or highly satisfied (or Equivalent score > 4 on Likert scale).', 2200, false);
