\i ./standard_prod.sql
\i ./measurable_element_prod.sql
\i ./checkpoint_prod.sql
\i ./restore-back.sql
\i ./dh/dh-standards.sql
\i ./dh/emergency.sql
\i ./dh/opd.sql
\i ./dh/Labour-Room.sql
\i ./dh/Maternity-Ward.sql
\i ./dh/Ped-Ward.sql
\i ./dh/SNCU.sql
\i ./dh/NRC.sql
\i ./dh/OT.sql
\i ./dh/M-OT.sql
\i ./dh/PP-Unit.sql
\i ./dh/ICU.sql
\i ./dh/IPD.sql
\i ./dh/Blood-Bank.sql
\i ./dh/Lab.sql
\i ./dh/Radiology.sql
\i ./dh/Pharmacy.sql
\i ./dh/Auxillary-services.sql
\i ./dh/Mortuary.sql
\i ./dh/Admin.sql
\i ./dh/cleanup.sql
