\i ./cleanup.sql
\i ./standards-me.sql
\i ./admin.sql
\i ./aux.sql
\i ./bsu.sql
\i ./emergency.sql
\i ./ipd.sql
\i ./lab.sql
\i ./labour-room-laq.sql
\i ./maternity.sql
\i ./mortuary.sql
\i ./nbsu.sql
\i ./nrc.sql
\i ./opd.sql
\i ./ot.sql
\i ./ped.sql
\i ./pharmacy.sql
\i ./radiology.sql
\i ./nqas-levels.sql
