insert into assessment_tool (name, assessment_tool_mode_id, sort_order) values ('HWC', (select id from assessment_tool_mode where name = 'Kayakalp'), 40);
insert into checklist (name, department_id) values ('HWC', (select id from department where name = 'Kayakalp'));
insert into assessment_tool_checklist (assessment_tool_id, checklist_id) values ((select max(id) from assessment_tool), (select max(id) from checklist));

insert into area_of_concern (name, reference) values ('Centre/Sub Centre level Health and Wellness Centre Upkeep', 'A');
insert into area_of_concern (name, reference) values ('Sanitation & Hygiene', 'B');
insert into area_of_concern (name, reference) values ('Waste Management', 'C');
insert into area_of_concern (name, reference) values ('Infection Control', 'D');
insert into area_of_concern (name, reference) values ('SUPPORT SERVICES', 'E');
insert into area_of_concern (name, reference) values ('Hygiene Promotion', 'F');
insert into area_of_concern (name, reference) values ('Beyond Hospital Boundary', 'G');

insert into checklist_area_of_concern (area_of_concern_id, checklist_id) VALUES ((select max(id) from area_of_concern where reference = 'A'), (select max(id) from checklist));
insert into checklist_area_of_concern (area_of_concern_id, checklist_id) VALUES ((select max(id) from area_of_concern where reference = 'B'), (select max(id) from checklist));
insert into checklist_area_of_concern (area_of_concern_id, checklist_id) VALUES ((select max(id) from area_of_concern where reference = 'C'), (select max(id) from checklist));
insert into checklist_area_of_concern (area_of_concern_id, checklist_id) VALUES ((select max(id) from area_of_concern where reference = 'D'), (select max(id) from checklist));
insert into checklist_area_of_concern (area_of_concern_id, checklist_id) VALUES ((select max(id) from area_of_concern where reference = 'E'), (select max(id) from checklist));
insert into checklist_area_of_concern (area_of_concern_id, checklist_id) VALUES ((select max(id) from area_of_concern where reference = 'F'), (select max(id) from checklist));
insert into checklist_area_of_concern (area_of_concern_id, checklist_id) VALUES ((select max(id) from area_of_concern where reference = 'G'), (select max(id) from checklist));


insert into standard (name, reference, area_of_concern_id) values ('Pest & Animal Control', 'A1', (select max(id) from area_of_concern where reference = 'A'));
insert into standard (name, reference, area_of_concern_id) values ('Landscaping, Gardening & Yoga', 'A2', (select max(id) from area_of_concern where reference = 'A'));
insert into standard (name, reference, area_of_concern_id) values ('Maintenance of Open Areas', 'A3', (select max(id) from area_of_concern where reference = 'A'));
insert into standard (name, reference, area_of_concern_id) values (' Hospital/Facility –Appearance', 'A4', (select max(id) from area_of_concern where reference = 'A'));
insert into standard (name, reference, area_of_concern_id) values ('Infrastructure Maintenance', 'A5', (select max(id) from area_of_concern where reference = 'A'));
insert into standard (name, reference, area_of_concern_id) values ('Illumination', 'A6', (select max(id) from area_of_concern where reference = 'A'));
insert into standard (name, reference, area_of_concern_id) values ('Maintenance of Furniture & Fixture', 'A7', (select max(id) from area_of_concern where reference = 'A'));
insert into standard (name, reference, area_of_concern_id) values ('Removal of Junk Material', 'A8', (select max(id) from area_of_concern where reference = 'A'));
insert into standard (name, reference, area_of_concern_id) values ('Water Conservation', 'A9', (select max(id) from area_of_concern where reference = 'A'));
insert into standard (name, reference, area_of_concern_id) values ('Work Place Management', 'A10', (select max(id) from area_of_concern where reference = 'A'));
insert into standard (name, reference, area_of_concern_id) values ('Cleanliness of Circulation Area (Corridors, Patient Waiting area)', 'B1', (select max(id) from area_of_concern where reference = 'B'));
insert into standard (name, reference, area_of_concern_id) values ('Cleanliness of Clinic room', 'B2', (select max(id) from area_of_concern where reference = 'B'));
insert into standard (name, reference, area_of_concern_id) values ('Cleanliness of Procedure Areas(Laboratory / Diagnostic)', 'B3', (select max(id) from area_of_concern where reference = 'B'));
insert into standard (name, reference, area_of_concern_id) values ('Cleanliness of Storage Space', 'B4', (select max(id) from area_of_concern where reference = 'B'));
insert into standard (name, reference, area_of_concern_id) values ('Cleanliness of Roof top', 'B5', (select max(id) from area_of_concern where reference = 'B'));
insert into standard (name, reference, area_of_concern_id) values ('Cleanliness of Toilets', 'B6', (select max(id) from area_of_concern where reference = 'B'));
insert into standard (name, reference, area_of_concern_id) values ('Use of standards materials and Equipment for Cleaning', 'B7', (select max(id) from area_of_concern where reference = 'B'));
insert into standard (name, reference, area_of_concern_id) values ('Use of Standard Methods for Cleaning', 'B8', (select max(id) from area_of_concern where reference = 'B'));
insert into standard (name, reference, area_of_concern_id) values ('Monitoring of Cleanliness Activities', 'B9', (select max(id) from area_of_concern where reference = 'B'));
insert into standard (name, reference, area_of_concern_id) values ('Drainage and Sewage Management', 'B10', (select max(id) from area_of_concern where reference = 'B'));
insert into standard (name, reference, area_of_concern_id) values ('Segregation of Biomedical Waste', 'C1', (select max(id) from area_of_concern where reference = 'C'));
insert into standard (name, reference, area_of_concern_id) values ('Collection and Transportation of Biomedical Waste', 'C2', (select max(id) from area_of_concern where reference = 'C'));
insert into standard (name, reference, area_of_concern_id) values ('Sharp Management', 'C3', (select max(id) from area_of_concern where reference = 'C'));
insert into standard (name, reference, area_of_concern_id) values ('Storage of Biomedical Waste', 'C4', (select max(id) from area_of_concern where reference = 'C'));
insert into standard (name, reference, area_of_concern_id) values ('Disposal of Biomedical waste', 'C5', (select max(id) from area_of_concern where reference = 'C'));
insert into standard (name, reference, area_of_concern_id) values ('Management Hazardous Waste', 'C6', (select max(id) from area_of_concern where reference = 'C'));
insert into standard (name, reference, area_of_concern_id) values ('Solid General Waste Management', 'C7', (select max(id) from area_of_concern where reference = 'C'));
insert into standard (name, reference, area_of_concern_id) values ('Liquid Waste Management', 'C8', (select max(id) from area_of_concern where reference = 'C'));
insert into standard (name, reference, area_of_concern_id) values ('Equipment and Supplies for Bio Medical Waste Management', 'C9', (select max(id) from area_of_concern where reference = 'C'));
insert into standard (name, reference, area_of_concern_id) values ('Statuary Compliances', 'C10', (select max(id) from area_of_concern where reference = 'C'));
insert into standard (name, reference, area_of_concern_id) values ('Hand Hygiene', 'D1', (select max(id) from area_of_concern where reference = 'D'));
insert into standard (name, reference, area_of_concern_id) values ('Personal Protective Equipment (PPE)', 'D2', (select max(id) from area_of_concern where reference = 'D'));
insert into standard (name, reference, area_of_concern_id) values ('Personal Protective Practices', 'D3', (select max(id) from area_of_concern where reference = 'D'));
insert into standard (name, reference, area_of_concern_id) values ('Decontamination and Cleaning of Instruments', 'D4', (select max(id) from area_of_concern where reference = 'D'));
insert into standard (name, reference, area_of_concern_id) values ('Reprocessing of reusable instruments and equipment', 'D5', (select max(id) from area_of_concern where reference = 'D'));
insert into standard (name, reference, area_of_concern_id) values ('Spill Management', 'D6', (select max(id) from area_of_concern where reference = 'D'));
insert into standard (name, reference, area_of_concern_id) values ('Isolation and Barrier Nursing', 'D7', (select max(id) from area_of_concern where reference = 'D'));
insert into standard (name, reference, area_of_concern_id) values ('Infection Control Program', 'D8', (select max(id) from area_of_concern where reference = 'D'));
insert into standard (name, reference, area_of_concern_id) values ('Surveillance Activity', 'D9', (select max(id) from area_of_concern where reference = 'D'));
insert into standard (name, reference, area_of_concern_id) values ('Environment Control', 'D10', (select max(id) from area_of_concern where reference = 'D'));
insert into standard (name, reference, area_of_concern_id) values ('Laundry Services & Linen Management', 'E1', (select max(id) from area_of_concern where reference = 'E'));
insert into standard (name, reference, area_of_concern_id) values ('Water Sanitation', 'E2', (select max(id) from area_of_concern where reference = 'E'));
insert into standard (name, reference, area_of_concern_id) values ('Storage Space', 'E3', (select max(id) from area_of_concern where reference = 'E'));
insert into standard (name, reference, area_of_concern_id) values ('Housekeeping services', 'E4', (select max(id) from area_of_concern where reference = 'E'));
insert into standard (name, reference, area_of_concern_id) values ('Outreach Services', 'E5', (select max(id) from area_of_concern where reference = 'E'));
insert into standard (name, reference, area_of_concern_id) values ('Community Monitoring & Patient Participation', 'F1', (select max(id) from area_of_concern where reference = 'F'));
insert into standard (name, reference, area_of_concern_id) values ('Information Education and Communication', 'F2', (select max(id) from area_of_concern where reference = 'F'));
insert into standard (name, reference, area_of_concern_id) values ('Leadership and Team work', 'F3', (select max(id) from area_of_concern where reference = 'F'));
insert into standard (name, reference, area_of_concern_id) values ('Training and Capacity Building and Standardization', 'F4', (select max(id) from area_of_concern where reference = 'F'));
insert into standard (name, reference, area_of_concern_id) values ('Staff Hygiene and Dress Code', 'F5', (select max(id) from area_of_concern where reference = 'F'));
insert into standard (name, reference, area_of_concern_id) values ('Promotion of Swachhata & Coordination with Local bodies', 'G1', (select max(id) from area_of_concern where reference = 'G'));
insert into standard (name, reference, area_of_concern_id) values ('Cleanliness of approach road and surrounding area ', 'G2', (select max(id) from area_of_concern where reference = 'G'));
insert into standard (name, reference, area_of_concern_id) values ('Aesthetics and amenities of Surrounding area', 'G3', (select max(id) from area_of_concern where reference = 'G'));
insert into standard (name, reference, area_of_concern_id) values ('Maintenance of surrounding area and Waste Management', 'G4', (select max(id) from area_of_concern where reference = 'G'));


insert into measurable_element (name, reference, standard_id) values ('No stray animals within the facility premises', 'A1.1', (select max(id) from standard where reference = 'A1'));
insert into measurable_element (name, reference, standard_id) values ('Pest Control Measures are implemented in the facility', 'A1.2', (select max(id) from standard where reference = 'A1'));
insert into measurable_element (name, reference, standard_id) values ('Surrounding area/ Open spaces are well maintained', 'A2.1', (select max(id) from standard where reference = 'A2'));
insert into measurable_element (name, reference, standard_id) values ('Provision of Yoga room ', 'A2.2', (select max(id) from standard where reference = 'A2'));
insert into measurable_element (name, reference, standard_id) values ('Approach walkway from gate to the facility is even and clean', 'A3.1', (select max(id) from standard where reference = 'A3'));
insert into measurable_element (name, reference, standard_id) values ('No water logging in open areas', 'A3.2', (select max(id) from standard where reference = 'A3'));
insert into measurable_element (name, reference, standard_id) values ('Walls are well-plastered ,painted and name of the facility is displayed ', 'A4.1', (select max(id) from standard where reference = 'A4'));
insert into measurable_element (name, reference, standard_id) values ('Branding of Health & Wellness Centre has been under taken as per current guideline.', 'A4.2', (select max(id) from standard where reference = 'A4'));
insert into measurable_element (name, reference, standard_id) values ('Facility Infrastructure is well maintained', 'A5.1', (select max(id) from standard where reference = 'A5'));
insert into measurable_element (name, reference, standard_id) values (' Centre  has intact boundary wall/Fencing and functional gates at entry  ', 'A5.2', (select max(id) from standard where reference = 'A5'));
insert into measurable_element (name, reference, standard_id) values ('Adequate illumination in inside and outside of the Centre', 'A6.1', (select max(id) from standard where reference = 'A6'));
insert into measurable_element (name, reference, standard_id) values ('Use of energy efficient bulbs', 'A6.2', (select max(id) from standard where reference = 'A6'));
insert into measurable_element (name, reference, standard_id) values ('Window and doors are maintained', 'A7.1', (select max(id) from standard where reference = 'A7'));
insert into measurable_element (name, reference, standard_id) values ('furniture and fixtures are in good condition.', 'A7.2', (select max(id) from standard where reference = 'A7'));
insert into measurable_element (name, reference, standard_id) values ('No junk material within  centre premises', 'A8.1', (select max(id) from standard where reference = 'A8'));
insert into measurable_element (name, reference, standard_id) values ('Centre  has system for removing junk materials', 'A8.2', (select max(id) from standard where reference = 'A8'));
insert into measurable_element (name, reference, standard_id) values ('Water supply system is maintained in the Centre ', 'A9.1', (select max(id) from standard where reference = 'A9'));
insert into measurable_element (name, reference, standard_id) values ('Check if the facility has rain-water harvesting system', 'A9.2', (select max(id) from standard where reference = 'A9'));
insert into measurable_element (name, reference, standard_id) values ('The Staff periodically sorts useful and unnecessary articles at work station', 'A10.1', (select max(id) from standard where reference = 'A10'));
insert into measurable_element (name, reference, standard_id) values ('The Staff arranges the useful articles, records in systematic manner and label them', 'A10.2', (select max(id) from standard where reference = 'A10'));
insert into measurable_element (name, reference, standard_id) values ('No dirt,grease,stains, cobwebs, bird nest, dust, vegetation on walls and roof in the  circulation area', 'B1.1', (select max(id) from standard where reference = 'B1'));
insert into measurable_element (name, reference, standard_id) values ('Corridors are cleaned at least once in the day with wet mop', 'B1.2', (select max(id) from standard where reference = 'B1'));
insert into measurable_element (name, reference, standard_id) values ('No dirt,grease,stains, cobwebs, bird nest, dust, vegetation on walls and roof in the Clinic room', 'B2.1', (select max(id) from standard where reference = 'B2'));
insert into measurable_element (name, reference, standard_id) values ('Clinic room is cleaned at least once in a day with wet mop', 'B2.2', (select max(id) from standard where reference = 'B2'));
insert into measurable_element (name, reference, standard_id) values ('No dirt,grease,stains, cobwebs, bird nest, dust, vegetation on walls and roof in the procedure area', 'B3.1', (select max(id) from standard where reference = 'B3'));
insert into measurable_element (name, reference, standard_id) values ('Procedure area are cleaned at least once in a day and as required', 'B3.2', (select max(id) from standard where reference = 'B3'));
insert into measurable_element (name, reference, standard_id) values ('No dirt, grease, stains, cobwebs, bird nest, dust, vegetation on walls and roof in the storage space.', 'B4.1', (select max(id) from standard where reference = 'B4'));
insert into measurable_element (name, reference, standard_id) values ('Storage space are cleaned at least once in the day with wet mop', 'B4.2', (select max(id) from standard where reference = 'B4'));
insert into measurable_element (name, reference, standard_id) values ('No dirt, cobwebs, bird nest, junk articles on roof top', 'B5.1', (select max(id) from standard where reference = 'B5'));
insert into measurable_element (name, reference, standard_id) values ('Roof top are cleaned at least once in the month', 'B5.2', (select max(id) from standard where reference = 'B5'));
insert into measurable_element (name, reference, standard_id) values ('No dirt/Grease/Stains/ Garbage in Toilets', 'B6.1', (select max(id) from standard where reference = 'B6'));
insert into measurable_element (name, reference, standard_id) values ('Separate male & female toilets have running water and functional cistern', 'B6.2', (select max(id) from standard where reference = 'B6'));
insert into measurable_element (name, reference, standard_id) values ('Availability of Detergent Disinfectant solution / Hospital Grade Phenyl for Cleaning purpose', 'B7.1', (select max(id) from standard where reference = 'B7'));
insert into measurable_element (name, reference, standard_id) values ('Availability of Cleaning Equipment', 'B7.2', (select max(id) from standard where reference = 'B7'));
insert into measurable_element (name, reference, standard_id) values ('Use of Two bucket system for cleaning', 'B8.1', (select max(id) from standard where reference = 'B8'));
insert into measurable_element (name, reference, standard_id) values ('Use unidirectional method and out word mopping', 'B8.2', (select max(id) from standard where reference = 'B8'));
insert into measurable_element (name, reference, standard_id) values ('Monitoring of cleanliness by Mid Level health provider (MLHP) on daily basis', 'B9.1', (select max(id) from standard where reference = 'B9'));
insert into measurable_element (name, reference, standard_id) values ('Periodic Monitoring of Housekeeping activities', 'B9.2', (select max(id) from standard where reference = 'B9'));
insert into measurable_element (name, reference, standard_id) values ('Availability of drainage and sewage system', 'B10.1', (select max(id) from standard where reference = 'B10'));
insert into measurable_element (name, reference, standard_id) values ('No blocked/ over-flowing drains in the facility', 'B10.2', (select max(id) from standard where reference = 'B10'));
insert into measurable_element (name, reference, standard_id) values ('Segregation of BMW is done as per BMW management rule,2016  & amendment', 'C1.1', (select max(id) from standard where reference = 'C1'));
insert into measurable_element (name, reference, standard_id) values ('Check if the staff is aware of segregation protocols', 'C1.2', (select max(id) from standard where reference = 'C1'));
insert into measurable_element (name, reference, standard_id) values (' Centre waste is collected and transported in safe manner', 'C2.1', (select max(id) from standard where reference = 'C2'));
insert into measurable_element (name, reference, standard_id) values ('The waste is transported in closed bag', 'C2.2', (select max(id) from standard where reference = 'C2'));
insert into measurable_element (name, reference, standard_id) values ('Disinfection of Broken / Discarded Glassware is done as per recommended procedure', 'C3.1', (select max(id) from standard where reference = 'C3'));
insert into measurable_element (name, reference, standard_id) values ('Sharp Waste is stored in Puncture proof containers', 'C3.2', (select max(id) from standard where reference = 'C3'));
insert into measurable_element (name, reference, standard_id) values ('BMW should not be stored more than recommended time', 'C4.1', (select max(id) from standard where reference = 'C4'));
insert into measurable_element (name, reference, standard_id) values ('Facility for storage of BMW', 'C4.2', (select max(id) from standard where reference = 'C4'));
insert into measurable_element (name, reference, standard_id) values ('Centre has adequate facility for disposal of Biomedical waste', 'C5.1', (select max(id) from standard where reference = 'C5'));
insert into measurable_element (name, reference, standard_id) values ('Facility manages recyclable waste as per approved procedure ', 'C5.2', (select max(id) from standard where reference = 'C5'));
insert into measurable_element (name, reference, standard_id) values ('Staff is aware of Mercury Spill management', 'C6.1', (select max(id) from standard where reference = 'C6'));
insert into measurable_element (name, reference, standard_id) values ('Availability of Mercury Spill Management Kit', 'C6.2', (select max(id) from standard where reference = 'C6'));
insert into measurable_element (name, reference, standard_id) values ('Disposal of General Waste', 'C7.1', (select max(id) from standard where reference = 'C7'));
insert into measurable_element (name, reference, standard_id) values ('Innovations in managing general waste', 'C7.2', (select max(id) from standard where reference = 'C7'));
insert into measurable_element (name, reference, standard_id) values ('Facility has provision of liquid waste management', 'C8.1', (select max(id) from standard where reference = 'C8'));
insert into measurable_element (name, reference, standard_id) values ('Liquid waste is made safe before mixing with other waste water', 'C8.2', (select max(id) from standard where reference = 'C8'));
insert into measurable_element (name, reference, standard_id) values ('Availability of Bins and plastic bags for segregation of waste at point of use', 'C9.1', (select max(id) from standard where reference = 'C9'));
insert into measurable_element (name, reference, standard_id) values ('Availability of Needle/ Hub cutter and puncture proof boxes', 'C9.2', (select max(id) from standard where reference = 'C9'));
insert into measurable_element (name, reference, standard_id) values ('Centre has a valid authorization for Bio Medical waste Management from the prescribed authority', 'C10.1', (select max(id) from standard where reference = 'C10'));
insert into measurable_element (name, reference, standard_id) values ('Centre maintains records, as required under the Biomedical Waste Rules 2016 and Amendment', 'C10.2', (select max(id) from standard where reference = 'C10'));
insert into measurable_element (name, reference, standard_id) values ('Availability of Sink and running water at point of use', 'D1.1', (select max(id) from standard where reference = 'D1'));
insert into measurable_element (name, reference, standard_id) values ('Staff is adheres to hand washing protocol', 'D1.2', (select max(id) from standard where reference = 'D1'));
insert into measurable_element (name, reference, standard_id) values ('Use of Gloves during procedures and examination', 'D2.1', (select max(id) from standard where reference = 'D2'));
insert into measurable_element (name, reference, standard_id) values ('Use of Masks, gloves and aprons', 'D2.2', (select max(id) from standard where reference = 'D2'));
insert into measurable_element (name, reference, standard_id) values ('The staff is aware of use of gloves, when to use (occasion) and its type', 'D3.1', (select max(id) from standard where reference = 'D3'));
insert into measurable_element (name, reference, standard_id) values ('No re-use of disposable personal protective equipment', 'D3.2', (select max(id) from standard where reference = 'D3'));
insert into measurable_element (name, reference, standard_id) values ('Staff knows how to make Chlorine solution', 'D4.1', (select max(id) from standard where reference = 'D4'));
insert into measurable_element (name, reference, standard_id) values ('Decontamination of instruments and Surfaces like examination table, dressing tables etc.', 'D4.2', (select max(id) from standard where reference = 'D4'));
insert into measurable_element (name, reference, standard_id) values ('Adherence to Protocols for items that come in contact with intact skin', 'D5.1', (select max(id) from standard where reference = 'D5'));
insert into measurable_element (name, reference, standard_id) values ('Adherence to Protocol for High Level disinfection', 'D5.2', (select max(id) from standard where reference = 'D5'));
insert into measurable_element (name, reference, standard_id) values ('Staff is aware of how to manage spills', 'D6.1', (select max(id) from standard where reference = 'D6'));
insert into measurable_element (name, reference, standard_id) values ('Spill management protocols are displayed at points if use', 'D6.2', (select max(id) from standard where reference = 'D6'));
insert into measurable_element (name, reference, standard_id) values ('Infectious patients are  separated from other patients ', 'D7.1', (select max(id) from standard where reference = 'D7'));
insert into measurable_element (name, reference, standard_id) values ('Staff is aware about Standard Precautions', 'D7.2', (select max(id) from standard where reference = 'D7'));
insert into measurable_element (name, reference, standard_id) values ('Monitoring of infection control practices', 'D8.1', (select max(id) from standard where reference = 'D8'));
insert into measurable_element (name, reference, standard_id) values ('Immunization and medical check-up of Service Providers', 'D8.2', (select max(id) from standard where reference = 'D8'));
insert into measurable_element (name, reference, standard_id) values ('Surveillance activity at the centre', 'D9.1', (select max(id) from standard where reference = 'D9'));
insert into measurable_element (name, reference, standard_id) values ('Facility reports all notifiable diseases and events', 'D9.2', (select max(id) from standard where reference = 'D9'));
insert into measurable_element (name, reference, standard_id) values ('Cross-ventilation ', 'D10.1', (select max(id) from standard where reference = 'D10'));
insert into measurable_element (name, reference, standard_id) values ('Preventive measures for air borne infections has been taken', 'D10.2', (select max(id) from standard where reference = 'D10'));
insert into measurable_element (name, reference, standard_id) values ('Available linens are clean', 'E1.1', (select max(id) from standard where reference = 'E1'));
insert into measurable_element (name, reference, standard_id) values ('Arrangements for washing linens', 'E1.2', (select max(id) from standard where reference = 'E1'));
insert into measurable_element (name, reference, standard_id) values ('The facility receives adequate quantity of water as per requirement', 'E2.1', (select max(id) from standard where reference = 'E2'));
insert into measurable_element (name, reference, standard_id) values ('There is storage tank for the water and tank is cleaned periodically', 'E2.2', (select max(id) from standard where reference = 'E2'));
insert into measurable_element (name, reference, standard_id) values ('Medicines are arranged systematically', 'E3.1', (select max(id) from standard where reference = 'E3'));
insert into measurable_element (name, reference, standard_id) values ('Cold storage equipment''s are clean and managed properly', 'E3.2', (select max(id) from standard where reference = 'E3'));
insert into measurable_element (name, reference, standard_id) values ('Routine Cleaning of the facility at least once in a day', 'E4.1', (select max(id) from standard where reference = 'E4'));
insert into measurable_element (name, reference, standard_id) values ('Thorough Cleaning of the facility fortnightly', 'E4.2', (select max(id) from standard where reference = 'E4'));
insert into measurable_element (name, reference, standard_id) values ('Biomedical waste generated during outreach session are transported to the  centre on the same day', 'E5.1', (select max(id) from standard where reference = 'E5'));
insert into measurable_element (name, reference, standard_id) values ('Reporting PHC monitor cleanliness and hygiene of outreach sessions and the center', 'E5.2', (select max(id) from standard where reference = 'E5'));
insert into measurable_element (name, reference, standard_id) values ('Patients are made aware of their responsibility of keeping the health facility clean', 'F1.1', (select max(id) from standard where reference = 'F1'));
insert into measurable_element (name, reference, standard_id) values ('Patient rights and responsibility are displayed', 'F1.2', (select max(id) from standard where reference = 'F1'));
insert into measurable_element (name, reference, standard_id) values ('IEC regarding importance of Hygiene practices are displayed', 'F2.1', (select max(id) from standard where reference = 'F2'));
insert into measurable_element (name, reference, standard_id) values ('IEC regarding Swachhta Abhiyan is displayed within the facilities’ premises', 'F2.2', (select max(id) from standard where reference = 'F2'));
insert into measurable_element (name, reference, standard_id) values ('Staff worked as a team to improve sanitation and hygiene of the facility', 'F3.1', (select max(id) from standard where reference = 'F3'));
insert into measurable_element (name, reference, standard_id) values ('Roles and responsibility of different staff members have been assigned and communicated', 'F3.2', (select max(id) from standard where reference = 'F3'));
insert into measurable_element (name, reference, standard_id) values ('Bio medical waste Management training has been provided to the staff', 'F4.1', (select max(id) from standard where reference = 'F4'));
insert into measurable_element (name, reference, standard_id) values ('Infection control Training has been provided to the staff', 'F4.2', (select max(id) from standard where reference = 'F4'));
insert into measurable_element (name, reference, standard_id) values ('Centre  has dress code policy for all cadre of staff', 'F5.1', (select max(id) from standard where reference = 'F5'));
insert into measurable_element (name, reference, standard_id) values ('There is a regular monitoring of hygiene of staff', 'F5.2', (select max(id) from standard where reference = 'F5'));
insert into measurable_element (name, reference, standard_id) values ('Facility is situated in ODF area', 'G1.1', (select max(id) from standard where reference = 'G1'));
insert into measurable_element (name, reference, standard_id) values ('Local community actively participates in VISHWAS campaign', 'G1.2', (select max(id) from standard where reference = 'G1'));
insert into measurable_element (name, reference, standard_id) values ('Implementation of IEC activities related to '' Swachh Bharat Abhiyan''', 'G1.3', (select max(id) from standard where reference = 'G1'));
insert into measurable_element (name, reference, standard_id) values ('The Facility coordinates with local Gram Panchayat and NGOs for improving the sanitation and hygiene', 'G1.4', (select max(id) from standard where reference = 'G1'));
insert into measurable_element (name, reference, standard_id) values ('The Facility coordinates with other departments for improving Swachhata', 'G1.5', (select max(id) from standard where reference = 'G1'));
insert into measurable_element (name, reference, standard_id) values ('Area around the facility is clean, neat & tidy', 'G2.1', (select max(id) from standard where reference = 'G2'));
insert into measurable_element (name, reference, standard_id) values ('On the way signages are available', 'G2.2', (select max(id) from standard where reference = 'G2'));
insert into measurable_element (name, reference, standard_id) values ('Approach road is clean and even', 'G2.3', (select max(id) from standard where reference = 'G2'));
insert into measurable_element (name, reference, standard_id) values ('All drain and sewer are covered. ', 'G2.4', (select max(id) from standard where reference = 'G2'));
insert into measurable_element (name, reference, standard_id) values ('Functional street lights are available along the approach road', 'G2.5', (select max(id) from standard where reference = 'G2'));
insert into measurable_element (name, reference, standard_id) values ('Parks and green areas of surrounding area are well maintained', 'G3.1', (select max(id) from standard where reference = 'G3'));
insert into measurable_element (name, reference, standard_id) values ('No unwanted/broken/ torn / loose hanging posters/ billboards.', 'G3.2', (select max(id) from standard where reference = 'G3'));
insert into measurable_element (name, reference, standard_id) values ('No loose hanging wires in and around the bill boards, electrical poles, etc.', 'G3.3', (select max(id) from standard where reference = 'G3'));
insert into measurable_element (name, reference, standard_id) values ('Availability of public toilets in surrounding area', 'G3.4', (select max(id) from standard where reference = 'G3'));
insert into measurable_element (name, reference, standard_id) values ('Availability of adequate parking stand in surrounding area', 'G3.5', (select max(id) from standard where reference = 'G3'));
insert into measurable_element (name, reference, standard_id) values ('Availability of garbage storage area', 'G4.2', (select max(id) from standard where reference = 'G4'));
insert into measurable_element (name, reference, standard_id) values ('Innovations in managing waste', 'G4.3', (select max(id) from standard where reference = 'G4'));
insert into measurable_element (name, reference, standard_id) values ('Surrounding areas are well maintained', 'G4.4', (select max(id) from standard where reference = 'G4'));
insert into measurable_element (name, reference, standard_id) values ('Regular repairs and maintained of roads', 'G4.5', (select max(id) from standard where reference = 'G4'));


insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('No stray animals within the facility premises', 'Observe for the presence of stray animals such as dogs, cats, cattle, pigs, etc. within the premises. Also discuss with the facility staff.
Also look at the breach, if any, in the boundary wall and presence of secured gate.
', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'A1.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Pest Control Measures are implemented in the facility', 'Check for the evidence at the facility ( Presence of Pests ,Record of Purchase/availability of Pesticides and availability of the rat trap) and interview the staff.', TRUE, TRUE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'A1.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Surrounding area/ Open spaces are well maintained', 'Check that wild vegetation does not exist. Shrubs and Trees are well maintained. Over grown branches of plants/ tree have been trimmed regularly.                                                Dry leaves and green waste are removed.', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'A2.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Provision of Yoga room ', 'Check for adequate space and cleanliness.', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'A2.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Approach walkway from gate to the facility is even and clean', 'Check that walkway is even and non-slippery and well maintained', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'A3.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('No water logging in open areas', 'Check for water accumulation in open areas because of faulty drainage, leakage from the pipes, etc.', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'A3.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Walls are well-plastered ,painted and name of the facility is displayed ', 'Check that wall plaster is not chipped-off and the building is painted with yellow color wall & Brown color windows.
The paint has not faded away. 
Name of the Centre is prominently displayed.
', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'A4.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Branding of Health & Wellness Centre has been under taken as per current guideline.', 'Check for:-
1- Outer surface of the building is yellow with specified shade.
2- Windows & their frame in the brown specified shade.
3- Six illustrations drawn on the façade.
4- Logo of NHM and Ayushman Bharat.
', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'A4.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Facility Infrastructure is well maintained', 'No major cracks, seepage, chipped plaster & floors in the  Centre .Periodic Maintenance is done.', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'A5.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values (' Centre  has intact boundary wall/Fencing and functional gates at entry  ', 'Check that there is a proper boundary wall/fencing of adequate height without any breach. ', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'A5.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Adequate illumination in inside and outside of the Centre', 'Check  for Adequate lighting arrangements through natural light or electric bulbs(CFL/LED) inside Centre .
Check that  Centre  front, entry gate and access road are well illuminated.
', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'A6.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Use of energy efficient bulbs', 'Check thatCentre uses energy efficient bulb like CFL or LED for lighting purpose within the Centre  Premises', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'A6.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Window and doors are maintained', 'Check, if Window panes are intact, and provided with Grill/ Wire Meshwork. Doors are intact and painted /varnished.', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'A7.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('furniture and fixtures are in good condition.', 'Check that Examination table, foot Step,  Table, Chair, stool, etc. are not rusted and are painted. Mattresses are clean and not torn
Almirah, Fan , Tube lights etc. are well maintained( As applicable)
', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'A7.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('No junk material within  centre premises', 'Check if unused/ condemned articles, and outdated records are kept in the haphazard manner.', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'A8.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Centre  has system for removing junk materials', 'Check for any system of removing junk from Centre  with support from PHC', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'A8.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Water supply system is maintained in the Centre ', 'Check for leaking taps, pipes, over-flowing tanks and dysfunctional cisterns.
Over-head tank is covered.
', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'A9.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Check if the facility has rain-water harvesting system', 'Check for its functionality and storage system', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'A9.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('The Staff periodically sorts useful and unnecessary articles at work station', 'Ask the Staff, how frequently they sort and remove unnecessary articles from their work place..
Check for presence of unnecessary articles.
', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'A10.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('The Staff arranges the useful articles, records in systematic manner and label them', 'Check if drugs, instruments, records are not lying in haphazard manner and kept near to point of use in systematic manner. The place has been demarcated for keeping different articles
Check that drugs, instruments, records, etc. are labelled for facilitating easy identification.
', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'A10.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('No dirt,grease,stains, cobwebs, bird nest, dust, vegetation on walls and roof in the  circulation area', 'Check that floors and walls of Corridors, Waiting area etc for any visible or tangible dirt, grease, stains, etc.
Check that roof, walls, corners of Corridors, Waiting area for any Cobweb, Bird Nest, etc.
', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'B1.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Corridors are cleaned at least once in the day with wet mop', 'Ask the staff about frequency of cleaning in a day.', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'B1.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('No dirt,grease,stains, cobwebs, bird nest, dust, vegetation on walls and roof in the Clinic room', 'Check floors and walls of the clinic room for any visible or tangible dirt, grease, stains, etc.
Check that roof, walls, corners of clinic for any Cobweb, Bird Nest, vegetation, etc.
', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'B2.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Clinic room is cleaned at least once in a day with wet mop', 'Ask staff about frequency of cleaning in a day. ', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'B2.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('No dirt,grease,stains, cobwebs, bird nest, dust, vegetation on walls and roof in the procedure area', 'Check that floors and walls of storage for any visible or tangible dirt, grease, stains, etc.
Check roof, walls, corners of these area for any cobweb, bird nest, vegetation, etc.

', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'B3.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Procedure area are cleaned at least once in a day and as required', 'Ask staff about frequency of cleaning in a day', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'B3.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('No dirt, grease, stains, cobwebs, bird nest, dust, vegetation on walls and roof in the storage space.', 'Check that floors and walls of storage for any visible or tangible dirt, grease, stains, etc.
Check roof, walls, corners of these area for any cobweb, bird nest, vegetation, etc.

', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'B4.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Storage space are cleaned at least once in the day with wet mop', 'Ask staff about frequency of cleaning in a day
', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'B4.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('No dirt, cobwebs, bird nest, junk articles on roof top', 'Check roof top of the Centre for any dirt, Cobweb, Bird Nest, etc.
Check for any junk articles on roof top
', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'B5.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Roof top are cleaned at least once in the month', 'Ask staff about frequency of cleaning ', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'B5.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('No dirt/Grease/Stains/ Garbage in Toilets', 'Check the toilets randomly for any visible dirt, grease, stains, water accumulation in toilets
Check for any foul smell in the Toilets', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'B6.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Separate male & female toilets have running water and functional cistern', 'Check availability of separate male and female toilets
Ask staff to operate cistern and water taps
', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'B6.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Availability of Detergent Disinfectant solution / Hospital Grade Phenyl for Cleaning purpose', 'Check for good quality cleaning solution preferably a ISI mark. Composition and concentration of solution is written on label. 
Check with staff if they are getting adequate supply. Verify the consumption records.
Check, if the cleaning staff is aware of correct concentration and dilution method for preparing cleaning solution.
', TRUE, TRUE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'B7.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Availability of Cleaning Equipment', 'Check the availability of mops, brooms, collection buckets etc. as per requirement. ', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'B7.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Use of Two bucket system for cleaning', 'Check if cleaning staff uses two bucket system for cleaning. One bucket for Cleaning solution, second for wringing the mop. Ask the cleaning staff about the process, Disinfection and washing of mops after every cleaning cycle', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'B8.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Use unidirectional method and out word mopping', 'Ask cleaning staff to demonstrate the how they apply mop on floors. It should be in one direction without returning to the starting point. 
The mop should move from inner area to outer area of the room. 
.', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'B8.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Monitoring of cleanliness by Mid Level health provider (MLHP) on daily basis', 'Ask Mid Level health provider (MLHP)  about monitoring mechanism of cleanliness. Check for records', TRUE, FALSE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'B9.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Periodic Monitoring of Housekeeping activities', 'Periodic Monitoring is done by Block Nodal office at least once in a month.', FALSE, TRUE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'B9.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Availability of drainage and sewage system', 'Centre has a functional septic tank and soak pit within the premises.', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'B10.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('No blocked/ over-flowing drains in the facility', 'Observe that the drains are not overflowing or blocked and they are covered.', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'B10.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Segregation of BMW is done as per BMW management rule,2016  & amendment', 'General & Biomedical Waste are not mixed together.        
Display of work instructions for segregation and handling of Biomedical waste                                                                                                                                
                                                                                                                            ', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'C1.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Check if the staff is aware of segregation protocols', 'Ask staff about the segregation protocol (Red bag for re-cyclable, Glassware into puncture proof and leak proof boxes and container with blue marking, etc.)', FALSE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'C1.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values (' Centre waste is collected and transported in safe manner', 'Check for records of linkage with CWTF operator or has functional deep burial pits within the facility.', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'C2.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('The waste is transported in closed bag', 'Check availability of bag for transportation of waste.', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'C2.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Disinfection of Broken / Discarded Glassware is done as per recommended procedure', 'Check if such waste is either pre-treated with 1% to 2% Sodium Hypochlorite (having 30% residual chlorine) for 20 minutes ', TRUE, TRUE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'C3.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Sharp Waste is stored in Puncture proof containers', 'Check availability of Puncture & leak proof container (White Translucent) at point of use for storing needles, syringes with fixed needles, needles etc.', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'C3.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('BMW should not be stored more than recommended time', 'Check if facility has functional Deep burial and sharp pit, they should dispose BMW on daily basis/ Facility having linkage with CTF should not store BMW more than 48 hours', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'C4.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Facility for storage of BMW', 'Facility with deep burial and sharp pit not required any storage facility/ Facility with linkage to CTF requires an isolated place with separate bins for storage of BMW ', FALSE, TRUE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'C4.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Centre has adequate facility for disposal of Biomedical waste', 'The Health facility within 75 KM of CTF shall have a valid contract with a Common Treatment facility for disposal of Bio medical waste. Or else facility should have Deep Burial Pit and Sharp Pit within premises of Health facility. Such deep burial pit should have approval of  the Prescribed Authority and would meet the norms.', TRUE, TRUE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'C5.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Facility manages recyclable waste as per approved procedure ', 'Check management of IV Bottles (Plastic), Syringes, etc.
(shredding/mutilation or a combination of sterilization and shredding and handed over to registered vendor are ensured after linkage with block PHC/CHC).
 
', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'C5.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Staff is aware of Mercury Spill management', 'Ask staff what he/she would do in case of Mercury spill. (If facility is mercury free, give full compliance)', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'C6.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Availability of Mercury Spill Management Kit', 'Check availability of Mercury Spill Management Kit.(If facility is mercury free, give full compliance)', FALSE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'C6.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Disposal of General Waste', 'There is a mechanism of removal of general waste from the facility and its disposal.', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'C7.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Innovations in managing general waste', 'Look for efforts of the health facility in managing General Waste, such as Recycling of paper waste, vermicomposting, waste to energy initiative, etc.', TRUE, TRUE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'C7.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Facility has provision of liquid waste management', 'Check for onsite provision of liquid waste disinfection set-up', TRUE, TRUE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'C8.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Liquid waste is made safe before mixing with other waste water', 'Check for the procedure - staff interview and direct observation', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'C8.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Availability of Bins and plastic bags for segregation of waste at point of use', 'One set of appropriate size bins at each point of generation for Biomedical and General waste.
Check all the bins are provided with chlorine free plastic bags. Ask staff about adequacy of supply.', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'C9.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Availability of Needle/ Hub cutter and puncture proof boxes', 'At each point of generation of sharp waste', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'C9.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Centre has a valid authorization for Bio Medical waste Management from the prescribed authority', 'Check for the validity of authorization certificate', FALSE, FALSE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'C10.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Centre maintains records, as required under the Biomedical Waste Rules 2016 and Amendment', 'Check following records -
a. Annual report submission
b. Yearly Health Check-up record of all handlers
c. BMW training records of all staff (once in year training)
d. Immunisation records
', FALSE, FALSE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'C10.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Availability of Sink and running water at point of use', 'Check for washbasin with functional tap, soap and running water at all points of use', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'D1.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Staff is adheres to hand washing protocol', 'Check Display of Hand washing Instructions
Ask facility staff to demonstrate 6 steps of normal hand wash and 5 moments of hand washing', FALSE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'D1.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Use of Gloves during procedures and examination', 'Check, if the staff uses gloves during examination, and while conducting procedures', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'D2.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Use of Masks, gloves and aprons', 'Check, if staff uses mask, gloves, aprons as applicable', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'D2.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('The staff is aware of use of gloves, when to use (occasion) and its type', 'Check with the staff when do they wear gloves, and when gloves are not required. The Staff should also know difference between clean & sterilized gloves and when to use', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'D3.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('No re-use of disposable personal protective equipment', 'Check that disposable gloves and mask are not re-used. Reusable Gloves and mask are used after adequate sterilization.', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'D3.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Staff knows how to make Chlorine solution', 'Ask the staff about the procedure of making chlorine solution and its frequency', FALSE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'D4.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Decontamination of instruments and Surfaces like examination table, dressing tables etc.', 'Check whether instruments are decontaminated with 0.5% chlorine solution for 10 minutes.  Check instruments are cleaned thoroughly with water and soap before sterilization
Ask staff  when and how they clean the surfaces either by chlorine solution or Disinfectant like carbolic acid', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'D4.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Adherence to Protocols for items that come in contact with intact skin', 'Check reusable instruments like thermometer, Stethoscope etc. are free from visible contamination and they are washed with soap and water before use.', TRUE, TRUE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'D5.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Adherence to Protocol for High Level disinfection', 'Check with the staff process about of High Level disinfection using Boiling for 20 minutes with lid on, soaking in 2% Glutaraldehyde/Chlorine solution for 20 minutes.', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'D5.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Staff is aware of how to manage spills', 'Check for adherence to protocols', FALSE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'D6.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Spill management protocols are displayed at points if use', 'Check for display', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'D6.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Infectious patients are  separated from other patients ', 'Check patients with respiratory infectious cases are separated from general patients in clinic room.', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'D7.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Staff is aware about Standard Precautions', 'Ask staff about Standard precautions and how they adhere to it.', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'D7.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Monitoring of infection control practices', 'Check if the Centre has a system to monitor infection control practices by Mid-level Health provider (MLHP) ,Village Health Sanitation and Nutrition Committee at least in a month.', FALSE, TRUE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'D8.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Immunization and medical check-up of Service Providers', 'Check record of staff, immunized against Hepatitis B and at least once a year medical check-up done.', FALSE, TRUE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'D8.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Surveillance activity at the centre', 'Check for surveillance about any abnormal increase in cases of diarrhea /dysentery, fever with rigors,
fever with rash, fever with jaundice or fever with unconsciousness and early reporting to concerned
PHC as per IDSP guidelines. 
', FALSE, TRUE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'D9.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Facility reports all notifiable diseases and events', 'Check facility has list of all notifiable disease needs immediate/periodic reporting to higher authority.
Check records that notifiable disease have been reported in program such as IDSP and AEFI Surveillance.', FALSE, TRUE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'D9.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Cross-ventilation ', 'Check availability of  Fans/ air conditioning/ Heating/ exhaust/ Ventilators as per environment condition and requirement', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'D10.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Preventive measures for air borne infections has been taken', 'Check location of the Centre , it should be away from Garbage dump
 Cattle shed, Stagnant pool, Pollution from industry
', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'D10.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Available linens are clean', 'Check linen such as table cloth, bedsheets, curtains etc. are clean and spotless', FALSE, TRUE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'E1.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Arrangements for washing linens', 'Check facility has in-house or outsourced arrangements for washing linens at least once in a week.', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'E1.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('The facility receives adequate quantity of water as per requirement', 'Water is available on 24x7 basis at all points of usage', FALSE, TRUE, TRUE, TRUE, (select max(id) from measurable_element where reference = 'E2.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('There is storage tank for the water and tank is cleaned periodically', 'The Centre have capacity to store 48 hours water requirement Water tank is cleaned at six monthly interval and records are maintained.', FALSE, FALSE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'E2.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Medicines are arranged systematically', 'Check all the shelves/racks containing medicines  are labelled in  Storage  and drug store.
Heavy items are stored at lower shelves/racks
Fragile items are not stored at the edges of the shelves
Drugs and consumables are stored away from water and sources of  heat, direct sunlight etc.
Drugs are not stored at floor and adjacent to wall



', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'E3.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Cold storage equipment''s are clean and managed properly', 'Check refrigerators / Ice packs are clean
Check if there is a practice of regular cleaning.
Cold box are not been used for purpose other than storing drugs and vaccines.
', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'E3.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Routine Cleaning of the facility at least once in a day', 'Cleaning includes dry and wet mopping', TRUE, FALSE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'E4.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Thorough Cleaning of the facility fortnightly', 'Thorough cleaning with warm water and soap/detergent', FALSE, TRUE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'E4.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Biomedical waste generated during outreach session are transported to the  centre on the same day', 'Check the records and ask staff', FALSE, TRUE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'E5.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Reporting PHC monitor cleanliness and hygiene of outreach sessions and the center', 'Check records that reporting PHC staff/In charge has checked cleanliness and hygiene of the centre and its outreach session at least monthly basis.', FALSE, TRUE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'E5.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Patients are made aware of their responsibility of keeping the health facility clean', 'Ask patients about their roles & responsibilities with regards to cleanliness. Patient’s responsibilities should be prominently displayed', TRUE, FALSE, TRUE, FALSE, (select max(id) from measurable_element where reference = 'F1.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Patient rights and responsibility are displayed', 'Check for IEC regarding the role and responsibility', TRUE, TRUE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'F1.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('IEC regarding importance of Hygiene practices are displayed', 'Check IEC regarding hand washing, water sanitation, use of toilets are displayed in local language', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'F2.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('IEC regarding Swachhta Abhiyan is displayed within the facilities’ premises', 'Should be displayed prominently in local language', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'F2.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Staff worked as a team to improve sanitation and hygiene of the facility', 'Ask staff about sanitation and hygiene', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'F3.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Roles and responsibility of different staff members have been assigned and communicated', 'Ask different members about their roles and responsibilities to make facility clean', FALSE, TRUE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'F3.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Bio medical waste Management training has been provided to the staff', 'Ask staff and look for any record', FALSE, TRUE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'F4.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Infection control Training has been provided to the staff', 'Check staff are trained at the time of induction and at least once in every year', FALSE, TRUE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'F4.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Centre  has dress code policy for all cadre of staff', 'Mid-Level Healthcare Provider and other health workers are in dress code.
Check for I card and name plates
', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'F5.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('There is a regular monitoring of hygiene of staff', 'Check about personal hygiene and clean dress of staff', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'F5.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Facility is situated in ODF area', 'Centre is located in ODF village', FALSE, TRUE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'G1.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Local community actively participates in VISHWAS campaign', 'Check for activities carried out under the leadership of VHSNCs for improving water, sanitation and hygiene situation during VISHWAS campaign.', FALSE, TRUE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'G1.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Implementation of IEC activities related to '' Swachh Bharat Abhiyan''', 'Check for any pamphlets/Posters/wall writing-promoting use of toilets, hand washing, safe drinking water and tree plantation etc. ', TRUE, TRUE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'G1.3'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('The Facility coordinates with local Gram Panchayat and NGOs for improving the sanitation and hygiene', 'Look for evidence of collective action for improving water, sanitation and hygiene. ', FALSE, TRUE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'G1.4'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('The Facility coordinates with other departments for improving Swachhata', 'Look for evidence of coordination with departments such as Education (school programs on hygiene promotions), Water and Sanitation (making area ODF), PWD (Repair & Maintenance), Forest Department (Plantation Drive) etc. which contributes strengthening towards of hygiene & sanitation', FALSE, TRUE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'G1.5'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Area around the facility is clean, neat & tidy', 'Check for any litter/garbage/refuse and water logging in the surrounding area of the facility.', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'G2.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('On the way signages are available', 'Check for directional signage with name of the facility on the approach road.', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'G2.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Approach road is clean and even', 'Check that approach road are clean and even', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'G2.3'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('All drain and sewer are covered. ', 'Check for overflowing drains surrounding the facility.', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'G2.4'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Functional street lights are available along the approach road', 'Check for street lights and their functionality. ', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'G2.5'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Parks and green areas of surrounding area are well maintained', 'Check that there no wild vegetation & growth in the surroundings. Shrubs and trees are well maintained.  Dry leaves and green waste are removed regularly.', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'G3.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('No unwanted/broken/ torn / loose hanging posters/ billboards.', 'Check that facility  surrounding are not studded with irrelevant and out dated posters, slogans, wall writings, graffiti, etc.', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'G3.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('No loose hanging wires in and around the bill boards, electrical poles, etc.', 'Check for any loose hanging wires.', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'G3.3'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Availability of public toilets in surrounding area', 'Check for separate toilets for male and female and they are conveniently located and clean.', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'G3.4'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Availability of adequate parking stand in surrounding area', 'Check for parking stand for auto/ rickshaw/taxi etc., and they are not parked haphazardly.', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'G3.5'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Availability of bins for General recyclable and biodegradable wastes', 'Check availability adequate number of bins for Biodegradable and recyclable general waste in the nearby area.', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'G4.1'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Availability of garbage storage area', 'Garbage storage area is away from residential/commercial areas and is covered/fenced. It is not causing public nuisance.', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'G4.2'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Innovations in managing waste', 'Check, if certain innovative practices have been introduced for managing general waste e.g. Vermicomposting, Re-cycling of papers, Waste to energy, Compost Activators, etc.', TRUE, TRUE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'G4.3'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Surrounding areas are well maintained', 'Check that there is no over grown shrubs, weeds, grass, potholes, bumps etc. in surrounding areas', TRUE, FALSE, FALSE, FALSE, (select max(id) from measurable_element where reference = 'G4.4'), (select max(id) from checklist));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Regular repairs and maintained of roads', 'Check current condition of the road', TRUE, TRUE, FALSE, TRUE, (select max(id) from measurable_element where reference = 'G4.5'), (select max(id) from checklist));


update assessment_tool set last_modified_date = current_timestamp, name = 'Health and Wellness Centre' where name = 'HWC';
