touch Emergency.sql
touch OPD.sql
touch Labour-Room.sql
touch Maternity-Ward.sql
touch Ped-Ward.sql
touch SNCU.sql
touch NRC.sql
touch OT.sql
touch PP-Unit.sql
touch ICU.sql
touch IPD.sql
touch Blood-Bank.sql
touch Lab.sql
touch Radiology.sql
touch Pharmacy.sql
touch Auxillary-services.sql
touch Mortuary.sql
touch Admin.sql
