DROP VIEW if exists checkpoint_scores_aoc;
DROP VIEW if exists checkpoint_scores_aoc_export;
drop VIEW IF EXISTS checkpoint_denormalised;
DROP view if exists assessment_denormalised;
DROP VIEW if exists checklist_score_view;
DROP VIEW if exists area_of_concern_score_view;
DROP VIEW if exists standard_score_view;
DROP VIEW if exists recent_facility_assessment_view;
DROP VIEW if exists checkpoint_score_denormalised;