-- select * from department;
insert into assessment_tool (name, assessment_tool_mode_id, type)
values ('MNH Program (Practices)', (select id from assessment_tool_mode where name = 'dakshata'), 'COMPLIANCE');

insert into checklist (name, department_id)
values ('MNH Program (Practices)', (select id from department where name = 'Labour Room'));
insert into assessment_tool_checklist (assessment_tool_id, checklist_id)
VALUES ((select max(id) from assessment_tool), (select max(id) from checklist));

insert into area_of_concern (name, reference) values ('MNH Program (Practices)', 'Form 4');
insert into checklist_area_of_concern (area_of_concern_id, checklist_id)
values ((select max(id) from area_of_concern), (select max(id) from checklist));


insert into standard (name, reference, area_of_concern_id) values ('Provider conducts an appropriate and adequate assessment of clinical condition of pregnant woman and fetus at the time of admission', 'Y1', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider conducts an appropriate and adequate assessment of clinical condition of pregnant woman and fetus at the time of admission', 'Y1', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider conducts an appropriate and adequate assessment of clinical condition of pregnant woman and fetus at the time of admission', 'Y1', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider conducts an appropriate and adequate assessment of clinical condition of pregnant woman and fetus at the time of admission', 'Y1', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider conducts an appropriate and adequate assessment of clinical condition of pregnant woman and fetus at the time of admission', 'Y1', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider assists the woman to have a safe and clean birth', 'Y10', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider assists the woman to have a safe and clean birth', 'Y10', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider assists the woman to have a safe and clean birth', 'Y10', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider assists the woman to have a safe and clean birth', 'Y10', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider assists the woman to have a safe and clean birth', 'Y10', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider conducts a rapid initial assessment and performs immediate newborn care (if baby cried immidiately)', 'Y11', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider conducts a rapid initial assessment and performs immediate newborn care (if baby cried immidiately)', 'Y11', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider conducts a rapid initial assessment and performs immediate newborn care (if baby cried immidiately)', 'Y11', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider conducts a rapid initial assessment and performs immediate newborn care (if baby cried immidiately)', 'Y11', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider conducts a rapid initial assessment and performs immediate newborn care (if baby cried immidiately)', 'Y11', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider conducts a rapid initial assessment and performs immediate newborn care (if baby cried immidiately)', 'Y11', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider conducts a rapid initial assessment and performs immediate newborn care (if baby cried immidiately)', 'Y11', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider performs newborn resuscitation if baby does not cry immediately after birth', 'Y12', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider performs newborn resuscitation if baby does not cry immediately after birth', 'Y12', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider performs newborn resuscitation if baby does not cry immediately after birth', 'Y12', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider performs newborn resuscitation if baby does not cry immediately after birth', 'Y12', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider performs newborn resuscitation if baby does not cry immediately after birth', 'Y12', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider performs newborn resuscitation if baby does not cry immediately after birth', 'Y12', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider performs Active Management of Third Stage of Labour (AMTSL)', 'Y13', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider performs Active Management of Third Stage of Labour (AMTSL)', 'Y13', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider performs Active Management of Third Stage of Labour (AMTSL)', 'Y13', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider performs Active Management of Third Stage of Labour (AMTSL)', 'Y13', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider performs Active Management of Third Stage of Labour (AMTSL)', 'Y13', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider identifies and manages Post Partum Haemorrhage', 'Y14', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider identifies and manages Post Partum Haemorrhage', 'Y14', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider identifies and manages Post Partum Haemorrhage', 'Y14', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider identifies and manages Post Partum Haemorrhage', 'Y14', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider identifies and manages Post Partum Haemorrhage', 'Y14', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider identifies and manages Post Partum Haemorrhage', 'Y14', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider identifies and manages Post Partum Haemorrhage', 'Y14', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider identifies and manages Post Partum Haemorrhage', 'Y14', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider assesses condition of mother and baby before shifting them from labour room', 'Y15', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider assesses condition of mother and baby before shifting them from labour room', 'Y15', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider assesses condition of mother and baby before shifting them from labour room', 'Y15', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider assesses condition of mother and baby before shifting them from labour room', 'Y15', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider assesses condition of mother and baby before shifting them from labour room', 'Y15', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('The facility adheres to universal infection prevention protocols', 'Y19', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('The facility adheres to universal infection prevention protocols', 'Y19', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('The facility adheres to universal infection prevention protocols', 'Y19', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('The facility adheres to universal infection prevention protocols', 'Y19', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('The facility adheres to universal infection prevention protocols', 'Y19', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('The facility adheres to universal infection prevention protocols', 'Y19', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider conducts internal examination appropriately', 'Y2', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider conducts internal examination appropriately', 'Y2', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider conducts internal examination appropriately', 'Y2', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider conducts internal examination appropriately', 'Y2', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider conducts internal examination appropriately', 'Y2', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider identifies and manages infection in pregnant woman', 'Y4', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider identifies and manages infection in pregnant woman', 'Y4', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider identifies and manages infection in pregnant woman', 'Y4', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider identifies and manages infection in pregnant woman', 'Y4', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider identifies and manages infection in pregnant woman', 'Y4', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider identifies conditions leading to preterm delivery and facilitates preventive care', 'Y5', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider identifies conditions leading to preterm delivery and facilitates preventive care', 'Y5', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider identifies conditions leading to preterm delivery and facilitates preventive care', 'Y5', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider identifies conditions leading to preterm delivery and facilitates preventive care', 'Y5', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider identifies conditions leading to preterm delivery and facilitates preventive care', 'Y5', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider identifies and manages severe Pre-eclampsia/Eclampsia (PE/E)', 'Y6', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider identifies and manages severe Pre-eclampsia/Eclampsia (PE/E)', 'Y6', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider identifies and manages severe Pre-eclampsia/Eclampsia (PE/E)', 'Y6', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider identifies and manages severe Pre-eclampsia/Eclampsia (PE/E)', 'Y6', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider identifies and manages severe Pre-eclampsia/Eclampsia (PE/E)', 'Y6', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider identifies and manages severe Pre-eclampsia/Eclampsia (PE/E)', 'Y6', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider monitors progress of labour in every case and adjusts care accordingly correctly fills partograph to monitor progress of labour and timely', 'Y7', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider monitors progress of labour in every case and adjusts care accordingly correctly fills partograph to monitor progress of labour and timely', 'Y7', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider monitors progress of labour in every case and adjusts care accordingly correctly fills partograph to monitor progress of labour and timely', 'Y7', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider monitors progress of labour in every case and adjusts care accordingly correctly fills partograph to monitor progress of labour and timely', 'Y7', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider prepares for safe care during delivery', 'Y9', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider prepares for safe care during delivery', 'Y9', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider prepares for safe care during delivery', 'Y9', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider prepares for safe care during delivery', 'Y9', (select max(id) from area_of_concern)) on conflict do nothing;
insert into standard (name, reference, area_of_concern_id) values ('Provider prepares for safe care during delivery', 'Y9', (select max(id) from area_of_concern)) on conflict do nothing;



insert into measurable_element (name, reference, standard_id) values ('Provider takes obstetric, medical and surgical history', 'Y1.1', (select max(standard.id) from standard where standard.reference = 'Y1')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider assesses gestational age correctly', 'Y1.2', (select max(standard.id) from standard where standard.reference = 'Y1')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider records fetal heart rate', 'Y1.3', (select max(standard.id) from standard where standard.reference = 'Y1')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider records mother’s BP', 'Y1.4', (select max(standard.id) from standard where standard.reference = 'Y1')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider records mother’s temperature', 'Y1.5', (select max(standard.id) from standard where standard.reference = 'Y1')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider ensures six ‘cleans’ while conducting delivery', 'Y10.1', (select max(standard.id) from standard where standard.reference = 'Y10')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider ensures six ‘cleans’ while conducting delivery', 'Y10.1', (select max(standard.id) from standard where standard.reference = 'Y10')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider ensures six ‘cleans’ while conducting delivery', 'Y10.1', (select max(standard.id) from standard where standard.reference = 'Y10')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider performs an episiotomy only if indicated', 'Y10.2', (select max(standard.id) from standard where standard.reference = 'Y10')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider allows spontaneous delivery of head by flexing it and giving perineal support; manages cord round the neck; assists delivery of shoulders and body', 'Y10.3', (select max(standard.id) from standard where standard.reference = 'Y10')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider delivers the baby on mother’s abdomen,', 'Y11.1', (select max(standard.id) from standard where standard.reference = 'Y11')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider ensures immediate drying, and asses breathing', 'Y11.2', (select max(standard.id) from standard where standard.reference = 'Y11')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider ensures immediate drying, and asses breathing', 'Y11.2', (select max(standard.id) from standard where standard.reference = 'Y11')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider performs delayed cord clamping and cutting', 'Y11.3', (select max(standard.id) from standard where standard.reference = 'Y11')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider ensures early initiation of breastfeeding', 'Y11.4', (select max(standard.id) from standard where standard.reference = 'Y11')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider weighs the baby and administers Vitamin K', 'Y11.5', (select max(standard.id) from standard where standard.reference = 'Y11')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider weighs the baby and administers Vitamin K', 'Y11.5', (select max(standard.id) from standard where standard.reference = 'Y11')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider performs steps for resuscitation within first 30 seconds:', 'Y12.1', (select max(standard.id) from standard where standard.reference = 'Y12')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider performs steps for resuscitation within first 30 seconds:', 'Y12.1', (select max(standard.id) from standard where standard.reference = 'Y12')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider initiates bag and mask ventilation for 30 seconds if baby still not breathing', 'Y12.2', (select max(standard.id) from standard where standard.reference = 'Y12')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider takes appropriate action if baby doesn’t respond to ambu bag ventilation after golden minute', 'Y12.3', (select max(standard.id) from standard where standard.reference = 'Y12')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider takes appropriate action if baby doesn’t respond to ambu bag ventilation after golden minute', 'Y12.3', (select max(standard.id) from standard where standard.reference = 'Y12')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider takes appropriate action if baby doesn’t respond to ambu bag ventilation after golden minute', 'Y12.3', (select max(standard.id) from standard where standard.reference = 'Y12')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider performs AMTSL and examines placenta thoroughly', 'Y13.1', (select max(standard.id) from standard where standard.reference = 'Y13')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider performs AMTSL and examines placenta thoroughly', 'Y13.1', (select max(standard.id) from standard where standard.reference = 'Y13')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider performs AMTSL and examines placenta thoroughly', 'Y13.1', (select max(standard.id) from standard where standard.reference = 'Y13')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider performs AMTSL and examines placenta thoroughly', 'Y13.1', (select max(standard.id) from standard where standard.reference = 'Y13')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider performs AMTSL and examines placenta thoroughly', 'Y13.1', (select max(standard.id) from standard where standard.reference = 'Y13')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider assesses uterine tone and bleeding per vaginum regularly after delivery', 'Y14.1', (select max(standard.id) from standard where standard.reference = 'Y14')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider performs all steps as per protocol in case of PPH', 'Y14.2', (select max(standard.id) from standard where standard.reference = 'Y14')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider performs all steps as per protocol in case of PPH', 'Y14.2', (select max(standard.id) from standard where standard.reference = 'Y14')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider performs all steps as per protocol in case of PPH', 'Y14.2', (select max(standard.id) from standard where standard.reference = 'Y14')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider performs all steps as per protocol in case of PPH', 'Y14.2', (select max(standard.id) from standard where standard.reference = 'Y14')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider performs all steps as per protocol in case of PPH', 'Y14.2', (select max(standard.id) from standard where standard.reference = 'Y14')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider performs all steps as per protocol in case of PPH', 'Y14.2', (select max(standard.id) from standard where standard.reference = 'Y14')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider performs all steps as per protocol in case of PPH', 'Y14.2', (select max(standard.id) from standard where standard.reference = 'Y14')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider looks for signs of infection in baby', 'Y15.1', (select max(standard.id) from standard where standard.reference = 'Y15')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider looks for signs of hypothermia in baby', 'Y15.2', (select max(standard.id) from standard where standard.reference = 'Y15')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider looks for signs of infection in mother', 'Y15.3', (select max(standard.id) from standard where standard.reference = 'Y15')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider looks for signs of infection in mother', 'Y15.3', (select max(standard.id) from standard where standard.reference = 'Y15')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider records BP of mother', 'Y15.4', (select max(standard.id) from standard where standard.reference = 'Y15')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Instruments and gloves are decontaminated after each use using Bleaching powder/ Sodium hypochlorite soln/Gluteraldehyde', 'Y19.1', (select max(standard.id) from standard where standard.reference = 'Y19')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Instruments and gloves are decontaminated after each use using Bleaching powder/ Sodium hypochlorite soln/Gluteraldehyde', 'Y19.1', (select max(standard.id) from standard where standard.reference = 'Y19')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Biomedical waste is segregated and disposed of as per the guidelines', 'Y19.2', (select max(standard.id) from standard where standard.reference = 'Y19')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Hand hygiene is performed before and after each procedure and sterile/HLD gloves are worn during delivery and internal examination', 'Y19.3', (select max(standard.id) from standard where standard.reference = 'Y19')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Follows universal precaution', 'Y19.4', (select max(standard.id) from standard where standard.reference = 'Y19')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Follows universal precaution', 'Y19.4', (select max(standard.id) from standard where standard.reference = 'Y19')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider conducts PV examination as per indication', 'Y2.1', (select max(standard.id) from standard where standard.reference = 'Y2')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider performs hand hygiene', 'Y2.2', (select max(standard.id) from standard where standard.reference = 'Y2')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider performs hand hygiene', 'Y2.2', (select max(standard.id) from standard where standard.reference = 'Y2')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider cleans the perineum appropriately before conducting PV examination', 'Y2.3', (select max(standard.id) from standard where standard.reference = 'Y2')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider records the finding of PV examination (in Case sheet/Partograph during active phase of labour)', 'Y2.4', (select max(standard.id) from standard where standard.reference = 'Y2')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider looks for signs of infection based on history and examination', 'Y4.1', (select max(standard.id) from standard where standard.reference = 'Y4')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider looks for signs of infection based on history and examination', 'Y4.1', (select max(standard.id) from standard where standard.reference = 'Y4')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider gives antibiotics only when indicated', 'Y4.2', (select max(standard.id) from standard where standard.reference = 'Y4')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider gives antibiotics only when indicated', 'Y4.2', (select max(standard.id) from standard where standard.reference = 'Y4')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider gives correct regimen of antibiotics', 'Y4.3', (select max(standard.id) from standard where standard.reference = 'Y4')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider does a correct estimation of gestational age to confirm that labour is pre term', 'Y5.1', (select max(standard.id) from standard where standard.reference = 'Y5')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider identifies conditions that may lead to pre term delivery', 'Y5.2', (select max(standard.id) from standard where standard.reference = 'Y5')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider appropriately administers antenatal corticosteroids to mothers', 'Y5.3', (select max(standard.id) from standard where standard.reference = 'Y5')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider appropriately administers antenatal corticosteroids to mothers', 'Y5.3', (select max(standard.id) from standard where standard.reference = 'Y5')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider ensures specialist attention', 'Y5.4', (select max(standard.id) from standard where standard.reference = 'Y5')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider identifies mothers with severe PE/E', 'Y6.1', (select max(standard.id) from standard where standard.reference = 'Y6')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider identifies mothers with severe PE/E', 'Y6.1', (select max(standard.id) from standard where standard.reference = 'Y6')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider gives correct regimen of Injn MgSO₄ for prevention and management of convulsions', 'Y6.2', (select max(standard.id) from standard where standard.reference = 'Y6')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider facilitates prescription of anti-hypertensives', 'Y6.3', (select max(standard.id) from standard where standard.reference = 'Y6')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider ensures specialist attention for care of mother and newborn', 'Y6.4', (select max(standard.id) from standard where standard.reference = 'Y6')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider performs nursing care', 'Y6.5', (select max(standard.id) from standard where standard.reference = 'Y6')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider timely uses partograph in every case.', 'Y7.1', (select max(standard.id) from standard where standard.reference = 'Y7')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider timely uses partograph in every case.', 'Y7.1', (select max(standard.id) from standard where standard.reference = 'Y7')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider correctly plots all parameters', 'Y7.2', (select max(standard.id) from standard where standard.reference = 'Y7')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider interprets partograph correctly and adjusts care according to findings', 'Y7.3', (select max(standard.id) from standard where standard.reference = 'Y7')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provder ensures sterile/HLD delivery tray is available', 'Y9.1', (select max(standard.id) from standard where standard.reference = 'Y9')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider ensures availability of pre-filled oxytocin syringe', 'Y9.2', (select max(standard.id) from standard where standard.reference = 'Y9')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider ensures functional items for newborn care and resuscitation', 'Y9.3', (select max(standard.id) from standard where standard.reference = 'Y9')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider ensures functional items for newborn care and resuscitation', 'Y9.3', (select max(standard.id) from standard where standard.reference = 'Y9')) on conflict do nothing;
insert into measurable_element (name, reference, standard_id) values ('Provider switches radiant warmer ‘on’ 30 min before childbirth', 'Y9.4', (select max(standard.id) from standard where standard.reference = 'Y9')) on conflict do nothing;


insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Takes obstetric, medical and surgical history', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y1.1'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Assesses gestational age through either LMP or Fundal height or USG (if available)', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y1.2'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Records fetal heart rate at admission', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y1.3'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Records mother`s BP at admission', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y1.4'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Records mother'' s temperature at admission', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y1.5'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Wears gloves on both the hands with correct technique', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y10.1'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Performs hand hygiene', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y10.1'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Ensures six cleans while conducting delivery', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y10.1'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Performs an episiotomy only if indicated', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y10.2'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Allows spontaneous delivery of head by flexing it and giving perineal support; manages cord round the neck; assists delivery of shoulders and body', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y10.3'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Delivers the baby on mother’s abdomen', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y11.1'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Two pre warmed clean towels are available', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y11.2'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('If breathing is normal, dries the baby immediately using first towel and then wraps in second warm towel', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y11.2'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Performs delayed cord clamping and cutting', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y11.3'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Initiates breast feeding within one hour of birth', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y11.4'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Weighs the baby', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y11.5'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Administers Vitamin K', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y11.5'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Performs following steps within first 30 seconds under radiant warmer: Positioning, Suctioning, Stimulation, Repositioning (PSSR)', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y12.1'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Performs following steps within first 30 seconds on mothers abdomen: Suction if indicated; dries the baby; immediate clamping and cutting the cord and shifting to radiant warmer if still not breathing', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y12.1'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Initiates bag and mask ventilation for 30 seconds if baby still not breathing', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y12.2'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Checks heart rate/cord pulsation', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y12.3'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Assesses breathing, if still not breathing continues bag and mask ventilation; starts oxygen', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y12.3'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Calls for advance help/arranges referral', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y12.3'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Palpates mothers abdomen to rule out second baby', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y13.1'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Performs uterine massage', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y13.1'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Administers Injn Oxytocin 10 I.U. IM/IV within one minute of delivery of baby', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y13.1'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Performs controlled cord traction (CCT) during contraction', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y13.1'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Checks placenta and membranes for completeness before discarding', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y13.1'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Assesses uterine tone and bleeding per vaginum regularly', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y14.1'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Administers uterotonics', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y14.2'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Manages shock if present', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y14.2'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Calls for help /asistance, while continue uterine message', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y14.2'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Treats specific cause of PPH', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y14.2'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Identifies specific cause of PPH', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y14.2'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Starts IV fluid', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y14.2'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Refers if required', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y14.2'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Looks for signs of infection in baby', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y15.1'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Measures baby''s temperature', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y15.2'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Looks for signs of infection in mother', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y15.3'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Records mother'' s temperature', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y15.3'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Records mother`s BP', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y15.4'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Instruments and gloves after is decontaminated after each use using chlorine soln/Gluteraldehyde (Gluteraldehyde for instruments)', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y19.1'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('0.5% chlorine solution is prepared daily', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y19.1'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Biomedical waste is segregated and disposed of as per the guidelines', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y19.2'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Hand hygiene is performed before and after each procedure and sterile/HLD gloves are worn during delivery and internal examination', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y19.3'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Delivery environment such as labour table, contaminated surfaces and floor are cleaned after each delivery', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y19.4'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Puts on PPE while conducting delivery', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y19.4'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Conducts PV examination only as indicated (4 hourly or based) on clinical indication', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y2.1'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Performs hand hygiene', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y2.2'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Wears gloves on both the hands with correct technique', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y2.2'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Cleans the perineum appropriately before conducting PV examination', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y2.3'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Records the finding of PV examination (in Case sheet/Partograph during active phase of labour)', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y2.4'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Records mother'' s temperature at admission', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y4.1'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Checks mother’s history related to maternal infection', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y4.1'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Assess the appropriateness of administration of antibiotics before discharge.', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y4.2'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Assess the appropriateness of administration of antibiotics at admission.', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y4.2'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Gives correct regimen of antibiotics', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y4.3'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Correctly estimates gestational age to confirm that labour is pre term through fundal height/LMP/USG (if available)', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y5.1'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Identifies condition that may lead to pre term delivery (severe Pre-eclampsia, Eclampsia, APH, Pre term Pre labour Rupture Of Membrane) and records them,', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y5.2'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Administers antenatal corticosteroids in pre term labour and conditions leading to pre term delivery (24-34 weeks)', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y5.3'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Gives correct regimen of corticosteroid', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y5.3'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Ensures specialist attention (care by Pediatrician)', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y5.4'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Records mother`s BP at admission', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y6.1'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Identifies danger signs or presence of convulsions', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y6.1'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Inj. MgSO4 is appropriately administered', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y6.2'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Facilitates prescription of anti-hypertensives', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y6.3'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Ensures specialist attention for care of mother and newborn', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y6.4'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Performs nursing care', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y6.5'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Attaches partograph in case sheet', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y7.1'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Initiates Partograph plotting once the Cx dilation is >=4 cm', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y7.1'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Plots all parameters', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y7.2'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Provider interprets partograph correctly and adjusts care according to findings', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y7.3'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Ensures required number of sterile/HLD delivery tray is available (2 trays per labor table),', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y9.1'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Ensures availability of pre-filled oxytocin syringe', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y9.2'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Ensures functional items for newborn care and resuscitation', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y9.3'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Designated new born corner is present', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y9.3'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
insert into checkpoint (name, means_of_verification, am_observation, am_staff_interview, am_patient_interview, am_record_review, measurable_element_id, checklist_id) values ('Switches radiant warmer ‘on’ 30 min before childbirth', 'NA', FALSE, FALSE, FALSE, FALSE, (select max(measurable_element.id) from measurable_element
 where measurable_element.reference = 'Y9.4'), (select max(id) from checklist where name = 'MNH Program (Practices)'));
