\i ./uphc/standards-me.sql
\i ./uphc/General-Clinic.sql
\i ./uphc/Maternity-Health.sql
\i ./uphc/New-Born-Child-Health.sql
\i ./uphc/Immunization.sql
\i ./uphc/Family-Planning.sql
\i ./uphc/Communicable-Disease.sql
\i ./uphc/NCD.sql
\i ./uphc/Dressing-Room-Emergency.sql
\i ./uphc/Pharmacy.sql
\i ./uphc/Lab.sql
\i ./uphc/Outreach.sql
\i ./uphc/General-Admin.sql
\i ./uphc/cleanup.sql

\i ./chc/standards-me.sql
\i ./chc/Accident-Emergency.sql
\i ./chc/Out-Patient-Department.sql
\i ./chc/Labour-room.sql
\i ./chc/In-Patient-Department.sql
\i ./chc/New-Born-Stabilization-Unit.sql
\i ./chc/Operation-Theatre.sql
\i ./chc/Laboratory.sql
\i ./chc/Radiology.sql
\i ./chc/Pharmacy-and-Stores.sql
\i ./chc/Blood-storage-unit.sql
\i ./chc/Auxillary-services.sql
\i ./chc/General-Administration.sql
\i ./chc/cleanup.sql
